# Определение стоимости автомобилей

Сервис по продаже автомобилей с пробегом «Не бит, не крашен» разрабатывает приложение для привлечения новых клиентов. В нём можно быстро узнать рыночную стоимость своего автомобиля. В вашем распоряжении исторические данные: технические характеристики, комплектации и цены автомобилей. Вам нужно построить модель для определения стоимости. 

Заказчику важны:

- качество предсказания;
- скорость предсказания;
- время обучения.

## Подготовка данных

На данном шаге:
- Импортируем библиотеки. 
- Откроем файл и изучим его.
- Проведем предобработку данных.

Для начала импортируем все необходимые библиотеки для работы:

In [1]:
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OrdinalEncoder 
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings('ignore')
import time

Откроем файл с данными.

In [2]:
df = pd.read_csv('/datasets/autos.csv')

Изучим первые 5 строк датасета.

In [3]:
df.head()

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
0,2016-03-24 11:52:17,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

Изучим общую информацию о датафреймах.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354369 entries, 0 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   DateCrawled        354369 non-null  object
 1   Price              354369 non-null  int64
 2   VehicleType        316879 non-null  object
 3   RegistrationYear   354369 non-null  int64
 4   Gearbox            334536 non-null  object
 5   Power              354369 non-null  int64
 6   Model              334664 non-null  object
 7   Kilometer          354369 non-null  int64
 8   RegistrationMonth  354369 non-null  int64
 9   FuelType           321474 non-null  object
 10  Brand              354369 non-null  object
 11  NotRepaired        283215 non-null  object
 12  DateCreated        354369 non-null  object
 13  NumberOfPictures   354369 non-null  int64
 14  PostalCode         354369 non-null  int64
 15  LastSeen           354369 non-null  object
dtypes: int64(7), object(9)
memory usage: 43.3+ MB

# Описание данных

Признаки 

- DateCrawled — дата скачивания анкеты из базы
- VehicleType — тип автомобильного кузова
- RegistrationYear — год регистрации автомобиля
- Gearbox — тип коробки передач
- Power — мощность (л. с.)
- Model — модель автомобиля
- Kilometer — пробег (км)
- RegistrationMonth — месяц регистрации автомобиля
- FuelType — тип топлива
- Brand — марка автомобиля
- NotRepaired — была машина в ремонте или нет
- DateCreated — дата создания анкеты
- NumberOfPictures — количество фотографий автомобиля
- PostalCode — почтовый индекс владельца анкеты (пользователя)
- LastSeen — дата последней активности пользователя

Целевой признак
- Price — цена (евро)

# Предобработка данных

Удалим ненужные столбцы с данными, которые не влияют на качество предсказания.

In [5]:
df = df.drop(["DateCrawled","DateCreated", 'RegistrationMonth',"LastSeen","NumberOfPictures","PostalCode"],axis = 1)

Проверим данные на наличие дубликатов.

In [6]:
df.duplicated().sum()

45040

Удалим дубликаты из датасета.

In [7]:
df.drop_duplicates(inplace=True)

Изучим численные показатели датафрейма.

In [8]:
df.describe()

               Price  RegistrationYear          Power      Kilometer
count  309329.000000     309329.000000  309329.000000  309329.000000
mean     4486.937196       2004.360105     110.976908  127217.735809
std      4564.852796         92.541399     200.969473   38532.941010
min         0.000000       1000.000000       0.000000    5000.000000
25%      1100.000000       1999.000000      69.000000  125000.000000
50%      2800.000000       2003.000000     105.000000  150000.000000
75%      6500.000000       2008.000000     143.000000  150000.000000
max     20000.000000       9999.000000   20000.000000  150000.000000

Видим, что в столбцах RegistrationYear, Power присутствуют аномальные значения. Необходимо их удалить. Напишем функцию, которая удалет выбросы методом межквартильного размаха.

In [9]:
def emission(df, column):
    q1 = df[column].quantile(q=0.25)
    q3 = df[column].quantile(q=0.75)
    norm = df.loc[(df[column] < q3 + 1.5*(q3 - q1)) & (df[column] > q1 - 1.5*(q3-q1)), column]
    return norm

emission_list = ['RegistrationYear','Power']
for item in emission_list:
    df[item] = emission(df, item)

Посмортим снова на численные показатели датафрейма.

In [10]:
df.describe()

               Price  RegistrationYear          Power      Kilometer
count  309329.000000     303327.000000  302599.000000  309329.000000
mean     4486.937196       2003.695500     102.665878  127217.735809
std      4564.852796          6.479498      57.149181   38532.941010
min         0.000000       1986.000000       0.000000    5000.000000
25%      1100.000000       1999.000000      68.000000  125000.000000
50%      2800.000000       2003.000000     102.000000  150000.000000
75%      6500.000000       2008.000000     140.000000  150000.000000
max     20000.000000       2019.000000     253.000000  150000.000000

In [11]:
df[df['Power']>=250]

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,FuelType,Brand,NotRepaired
190,11299,sedan,2006.0,auto,250.0,golf,150000,petrol,volkswagen,no
661,9900,suv,2000.0,auto,250.0,NaN,150000,lpg,sonstige_autos,no
1137,5699,wagon,2004.0,auto,250.0,a6,150000,petrol,audi,NaN
1271,9999,suv,2005.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
1557,7999,coupe,2004.0,auto,250.0,a3,150000,petrol,audi,no
2152,5000,suv,2002.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
2388,3330,sedan,1991.0,auto,252.0,other,150000,petrol,mercedes_benz,no
2699,4990,wagon,2003.0,auto,250.0,other,150000,petrol,saab,no
3026,14999,convertible,2000.0,manual,252.0,boxster,125000,petrol,porsche,no
3319,18500,wagon,2013.0,manual,250.0,focus,60000,petrol,ford,no
3837,6595,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,NaN
4094,17000,coupe,2011.0,manual,250.0,megane,60000,petrol,renault,no
4202,4199,small,2004.0,manual,250.0,other,150000,petrol,audi,no
4675,14500,wagon,2006.0,auto,250.0,a3,150000,petrol,audi,no
4784,8900,sedan,2004.0,auto,250.0,a3,150000,petrol,audi,no
5730,13900,sedan,2006.0,manual,250.0,golf,125000,petrol,volkswagen,no
6243,6990,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
6247,3499,sedan,1998.0,manual,250.0,5er,150000,petrol,bmw,no
6427,11299,wagon,2006.0,auto,250.0,golf,150000,petrol,volkswagen,NaN
7423,4999,wagon,2002.0,manual,250.0,other,150000,petrol,saab,no
7610,5500,wagon,2002.0,auto,250.0,other,150000,petrol,saab,no
8141,19999,suv,2014.0,auto,250.0,grand,90000,gasoline,jeep,yes
8512,6999,suv,2003.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
9089,7000,wagon,2003.0,auto,250.0,156,150000,petrol,alfa_romeo,no
9713,6799,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,NaN
10583,18900,convertible,2001.0,manual,252.0,boxster,70000,petrol,porsche,no
12819,19500,NaN,2017.0,auto,250.0,tt,80000,NaN,audi,NaN
13498,0,coupe,2011.0,manual,250.0,megane,60000,petrol,renault,no
14531,6800,suv,2001.0,auto,250.0,m_klasse,125000,gasoline,mercedes_benz,yes
14868,1700,sedan,2004.0,auto,250.0,s60,150000,petrol,volvo,yes
16008,11800,suv,2005.0,manual,250.0,cayenne,125000,petrol,porsche,no
16034,19900,NaN,1990.0,manual,250.0,other,150000,NaN,porsche,no
16607,13499,suv,2005.0,auto,250.0,cayenne,150000,petrol,porsche,no
16921,12500,suv,2004.0,auto,250.0,cayenne,150000,lpg,porsche,no
17125,10499,convertible,2007.0,auto,250.0,eos,125000,petrol,volkswagen,no
17150,0,NaN,2017.0,manual,250.0,golf,150000,petrol,volkswagen,NaN
17939,7500,wagon,2006.0,auto,250.0,passat,150000,petrol,volkswagen,no
18312,20000,wagon,2011.0,manual,250.0,insignia,50000,petrol,opel,no
18399,14999,sedan,2006.0,auto,250.0,golf,125000,petrol,volkswagen,no
19244,14500,sedan,NaN,auto,250.0,NaN,70000,petrol,sonstige_autos,no
19922,4950,suv,2002.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
20526,6490,sedan,2005.0,manual,250.0,golf,150000,petrol,volkswagen,no
21357,5500,suv,2002.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
22179,8500,suv,2003.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
22412,9900,sedan,2006.0,manual,250.0,golf,150000,petrol,volkswagen,yes
23010,11999,sedan,2006.0,auto,250.0,golf,150000,petrol,volkswagen,no
23268,5500,sedan,2006.0,auto,250.0,passat,150000,petrol,volkswagen,no
23409,11800,sedan,2006.0,manual,250.0,golf,150000,petrol,volkswagen,no
23533,12500,suv,2005.0,auto,250.0,cayenne,150000,petrol,porsche,NaN
23835,14900,convertible,2007.0,auto,250.0,tt,150000,petrol,audi,no
24265,18000,other,1988.0,auto,250.0,other,150000,petrol,chevrolet,no
24863,8000,sedan,2004.0,auto,250.0,5er,150000,NaN,bmw,NaN
25027,8500,NaN,2017.0,manual,250.0,leon,150000,NaN,seat,NaN
25058,16799,coupe,2007.0,manual,253.0,tt,70000,petrol,audi,no
25406,15000,coupe,1990.0,manual,250.0,911,150000,petrol,porsche,yes
25606,15500,sedan,2006.0,auto,250.0,golf,125000,petrol,volkswagen,no
26521,3499,suv,2002.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
27212,10900,suv,2003.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
28482,9900,suv,2005.0,auto,250.0,cayenne,150000,petrol,porsche,no
28508,13000,coupe,2011.0,manual,250.0,megane,125000,petrol,renault,no
29259,6390,wagon,2005.0,auto,250.0,a3,150000,petrol,audi,no
29369,8490,wagon,2005.0,auto,250.0,a3,150000,petrol,audi,no
29789,7400,suv,2002.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
30338,3750,wagon,2000.0,manual,250.0,v70,150000,petrol,volvo,no
30986,16250,sedan,2011.0,manual,250.0,golf,70000,petrol,volkswagen,no
31285,11111,convertible,2007.0,auto,250.0,eos,150000,petrol,volkswagen,no
31934,18500,suv,2002.0,auto,250.0,NaN,150000,lpg,sonstige_autos,no
32266,13900,coupe,NaN,manual,252.0,other,90000,petrol,ford,no
32351,14900,convertible,2001.0,manual,252.0,boxster,150000,petrol,porsche,no
33181,8250,coupe,2005.0,auto,250.0,a3,150000,petrol,audi,no
33784,5499,wagon,2006.0,auto,250.0,signum,150000,petrol,opel,no
34358,4999,suv,1998.0,auto,250.0,NaN,150000,petrol,sonstige_autos,no
34745,7000,coupe,2005.0,auto,250.0,tt,150000,petrol,audi,yes
34893,10999,suv,2005.0,manual,250.0,cayenne,150000,petrol,porsche,NaN
35311,4199,bus,2003.0,auto,253.0,other,150000,lpg,chrysler,no
35341,10900,wagon,2005.0,manual,250.0,a3,100000,petrol,audi,no
35472,17900,coupe,2008.0,auto,250.0,tt,125000,petrol,audi,no
35789,13986,convertible,2001.0,manual,252.0,boxster,150000,petrol,porsche,no
35864,4500,NaN,2016.0,auto,250.0,NaN,150000,petrol,audi,yes
35868,7500,coupe,2004.0,auto,250.0,tt,150000,petrol,audi,NaN
36389,8399,coupe,2004.0,auto,250.0,a3,150000,petrol,audi,no
36727,12990,coupe,2006.0,auto,250.0,tt,125000,petrol,audi,no
36778,13900,suv,2005.0,auto,250.0,cayenne,150000,petrol,porsche,NaN
37349,4500,sedan,1998.0,manual,250.0,5er,150000,petrol,bmw,no
37398,14499,coupe,2007.0,manual,250.0,tt,150000,petrol,audi,no
37489,5500,sedan,2004.0,auto,250.0,NaN,150000,NaN,audi,no
37631,1850,sedan,1993.0,auto,250.0,other,150000,petrol,audi,no
37842,10500,sedan,2006.0,manual,250.0,golf,150000,petrol,volkswagen,no
38079,15000,sedan,2011.0,manual,250.0,a3,100000,petrol,audi,no
38494,17449,coupe,2006.0,auto,252.0,golf,90000,petrol,volkswagen,no
39316,9500,coupe,1995.0,auto,250.0,other,125000,petrol,porsche,no
39606,18250,sedan,2012.0,manual,250.0,focus,60000,petrol,ford,no
39717,6850,sedan,2002.0,auto,250.0,s_klasse,150000,gasoline,mercedes_benz,no
40200,6250,sedan,2005.0,manual,250.0,golf,150000,petrol,volkswagen,no
42420,6900,wagon,2004.0,auto,250.0,e_klasse,150000,gasoline,mercedes_benz,no
42802,8900,coupe,2004.0,auto,250.0,tt,150000,petrol,audi,no
43955,10999,suv,2004.0,manual,250.0,cayenne,150000,petrol,porsche,no
44246,14800,sedan,2006.0,auto,250.0,golf,125000,petrol,volkswagen,no
44382,18700,sedan,2008.0,manual,250.0,golf,60000,petrol,volkswagen,no
44684,12900,coupe,2007.0,manual,250.0,tt,150000,petrol,audi,no
45034,12900,coupe,NaN,auto,250.0,NaN,70000,petrol,sonstige_autos,no
45154,6500,sedan,NaN,auto,250.0,s_klasse,150000,petrol,mercedes_benz,NaN
45336,12000,sedan,2005.0,auto,250.0,golf,150000,petrol,volkswagen,no
45586,7500,NaN,2005.0,auto,250.0,tt,150000,NaN,audi,no
45615,5950,sedan,2005.0,manual,250.0,golf,150000,petrol,volkswagen,no
45767,300,sedan,1988.0,manual,250.0,golf,150000,petrol,volkswagen,NaN
45981,3900,wagon,2004.0,manual,250.0,ptcruiser,150000,petrol,chrysler,no
46137,17990,coupe,2008.0,auto,250.0,tt,125000,petrol,audi,no
46156,12490,sedan,2005.0,auto,250.0,golf,150000,petrol,volkswagen,no
46196,17800,convertible,2007.0,auto,250.0,tt,60000,petrol,audi,no
46683,12500,suv,2004.0,manual,250.0,cayenne,100000,petrol,porsche,no
46794,0,coupe,1990.0,NaN,250.0,911,100000,petrol,porsche,NaN
48004,19000,wagon,2013.0,manual,250.0,focus,30000,petrol,ford,no
48104,4800,coupe,1999.0,manual,253.0,other,50000,petrol,fiat,no
49107,16950,sedan,2006.0,auto,250.0,golf,90000,petrol,volkswagen,no
49253,15900,convertible,2007.0,auto,250.0,tt,125000,petrol,audi,no
49279,19500,wagon,2013.0,manual,250.0,focus,30000,petrol,ford,no
49593,8000,sedan,2005.0,auto,250.0,other,150000,petrol,ford,no
50459,4100,wagon,2002.0,auto,250.0,a6,150000,petrol,audi,no
51610,16500,coupe,2008.0,manual,250.0,tt,125000,petrol,audi,no
51649,14600,suv,2009.0,manual,250.0,kuga,70000,petrol,ford,no
52303,9100,small,2005.0,manual,250.0,golf,150000,petrol,volkswagen,no
52377,7550,sedan,2002.0,auto,250.0,s_klasse,150000,gasoline,mercedes_benz,no
54233,6750,sedan,2004.0,manual,250.0,a3,20000,petrol,audi,no
54612,6499,sedan,2005.0,auto,250.0,NaN,150000,NaN,volkswagen,no
55518,8750,NaN,2016.0,auto,250.0,tt,150000,petrol,audi,NaN
55649,6900,sedan,2003.0,manual,250.0,leon,150000,petrol,seat,no
56352,12800,sedan,2006.0,auto,250.0,golf,150000,petrol,volkswagen,no
56439,14800,coupe,2003.0,auto,250.0,tt,100000,petrol,audi,no
57179,9999,suv,2002.0,auto,250.0,cayenne,150000,lpg,porsche,no
57347,990,suv,2002.0,auto,250.0,NaN,150000,lpg,sonstige_autos,no
58097,11500,suv,2004.0,auto,250.0,cayenne,150000,petrol,porsche,no
59344,8499,suv,2003.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
60086,7800,small,2002.0,manual,250.0,a3,150000,petrol,audi,no
60462,19200,sedan,2013.0,manual,250.0,focus,40000,petrol,ford,no
60550,5998,sedan,2006.0,auto,250.0,passat,150000,petrol,volkswagen,no
61077,4999,NaN,2001.0,auto,250.0,NaN,150000,NaN,audi,no
61416,14000,sedan,2006.0,auto,250.0,golf,20000,petrol,volkswagen,no
61447,7200,suv,2003.0,auto,250.0,m_klasse,5000,NaN,mercedes_benz,no
61546,6800,suv,2003.0,auto,250.0,m_klasse,150000,petrol,mercedes_benz,NaN
62514,4400,coupe,1999.0,manual,253.0,other,50000,petrol,fiat,no
62653,12500,suv,2005.0,auto,250.0,cayenne,150000,petrol,porsche,no
62818,16950,sedan,2006.0,manual,250.0,golf,90000,petrol,volkswagen,no
62829,8550,convertible,1991.0,manual,250.0,911,125000,petrol,porsche,no
63582,10999,wagon,2005.0,manual,250.0,a3,150000,petrol,audi,no
63648,10990,coupe,2004.0,auto,250.0,tt,125000,petrol,audi,no
63765,15450,convertible,2000.0,manual,252.0,boxster,150000,petrol,porsche,no
64134,11990,convertible,2008.0,auto,250.0,eos,90000,petrol,volkswagen,no
64180,14990,sedan,2007.0,auto,250.0,golf,150000,petrol,volkswagen,no
64275,4500,suv,2003.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
64640,8900,wagon,2005.0,auto,250.0,a3,90000,petrol,audi,no
64707,1800,wagon,2003.0,manual,250.0,other,150000,petrol,saab,yes
65080,6390,coupe,2004.0,auto,250.0,tt,150000,petrol,audi,no
65082,12000,coupe,2006.0,auto,250.0,tt,150000,petrol,audi,no
65264,15900,coupe,2007.0,auto,250.0,tt,100000,petrol,audi,no
65495,6300,sedan,2005.0,manual,250.0,golf,150000,petrol,volkswagen,no
66743,3790,sedan,2000.0,auto,252.0,other,150000,petrol,chrysler,no
67453,9700,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
67647,12500,sedan,2007.0,auto,250.0,NaN,150000,gasoline,bmw,no
68459,7200,sedan,2003.0,auto,250.0,phaeton,150000,petrol,volkswagen,NaN
68483,8990,sedan,2004.0,auto,250.0,s_klasse,150000,gasoline,mercedes_benz,no
69178,14999,suv,2005.0,auto,250.0,cayenne,150000,petrol,porsche,no
69566,6000,NaN,2017.0,manual,250.0,a6,150000,NaN,audi,NaN
69649,17500,convertible,2007.0,manual,250.0,tt,60000,petrol,audi,no
69918,1500,suv,NaN,auto,250.0,other,150000,petrol,chevrolet,no
69959,15900,convertible,2001.0,manual,252.0,boxster,100000,petrol,porsche,no
70150,19800,sedan,2007.0,auto,250.0,golf,80000,petrol,volkswagen,no
70492,9500,wagon,2006.0,auto,250.0,passat,150000,petrol,volkswagen,no
71113,16750,coupe,2006.0,manual,253.0,tt,100000,petrol,audi,NaN
71275,11500,convertible,1999.0,manual,252.0,boxster,150000,petrol,porsche,NaN
71771,9500,wagon,2005.0,auto,250.0,a3,150000,petrol,audi,no
72017,19800,sedan,2008.0,auto,250.0,golf,90000,petrol,volkswagen,no
72339,10499,wagon,2006.0,auto,250.0,a3,150000,petrol,audi,no
72916,8000,sedan,2001.0,manual,250.0,other,150000,petrol,audi,no
72942,6500,sedan,2004.0,auto,250.0,a3,150000,petrol,audi,no
73015,13700,sedan,2008.0,auto,250.0,golf,150000,petrol,volkswagen,no
73158,50,sedan,2014.0,manual,250.0,focus,20000,NaN,ford,no
73955,6950,wagon,1998.0,manual,250.0,v70,150000,petrol,volvo,NaN
74254,0,sedan,2000.0,NaN,250.0,NaN,150000,NaN,chrysler,NaN
75095,8888,wagon,2003.0,auto,250.0,other,150000,petrol,saab,no
75132,3390,suv,2003.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
75175,8950,suv,2002.0,auto,250.0,NaN,150000,petrol,sonstige_autos,no
75261,11200,suv,2002.0,auto,250.0,m_klasse,125000,gasoline,mercedes_benz,no
75290,6500,wagon,2005.0,auto,250.0,5er,150000,gasoline,bmw,no
75479,12999,coupe,2003.0,auto,250.0,tt,80000,petrol,audi,no
75682,10600,sedan,2005.0,manual,250.0,golf,150000,petrol,volkswagen,no
75800,599,sedan,2001.0,auto,252.0,other,150000,petrol,chrysler,yes
76411,20000,sedan,NaN,auto,250.0,s_klasse,20000,petrol,mercedes_benz,NaN
76599,9500,sedan,2006.0,manual,250.0,golf,150000,petrol,volkswagen,no
77755,4250,sedan,2004.0,manual,250.0,s60,150000,lpg,volvo,NaN
78351,4000,sedan,1990.0,auto,252.0,s_klasse,150000,petrol,mercedes_benz,NaN
79077,3999,sedan,1998.0,manual,250.0,5er,150000,petrol,bmw,no
79391,6480,wagon,2003.0,manual,250.0,a6,150000,petrol,audi,no
79492,13990,coupe,2004.0,auto,250.0,tt,150000,petrol,audi,no
80089,8600,small,2003.0,manual,250.0,a3,150000,petrol,audi,no
80921,15000,convertible,2004.0,auto,250.0,tt,150000,petrol,audi,no
81459,523,sedan,2012.0,auto,250.0,a8,50000,gasoline,audi,no
81464,3999,wagon,2003.0,manual,250.0,156,150000,petrol,alfa_romeo,no
82445,5999,NaN,2016.0,manual,250.0,a6,150000,NaN,audi,no
82696,7990,NaN,2017.0,manual,250.0,a3,150000,petrol,audi,no
82760,6500,NaN,2005.0,auto,250.0,a3,150000,NaN,audi,no
82791,11300,suv,2004.0,auto,250.0,cayenne,150000,petrol,porsche,no
83084,12000,suv,2006.0,auto,250.0,cayenne,150000,petrol,porsche,no
83935,12800,suv,2006.0,manual,250.0,cayenne,150000,petrol,porsche,no
84550,7900,sedan,2004.0,manual,250.0,a3,125000,petrol,audi,no
85242,1555,sedan,2000.0,auto,252.0,other,150000,petrol,chrysler,yes
85626,8000,wagon,2004.0,auto,250.0,a3,150000,petrol,audi,no
85741,10900,wagon,2006.0,auto,250.0,a3,150000,petrol,audi,no
86129,5800,wagon,2002.0,manual,250.0,a6,150000,petrol,audi,no
86147,19900,convertible,NaN,auto,250.0,other,100000,petrol,chevrolet,NaN
86405,9000,coupe,2004.0,manual,250.0,tt,150000,petrol,audi,no
87360,11699,wagon,2006.0,auto,250.0,a3,70000,petrol,audi,no
87792,10500,suv,2006.0,NaN,250.0,cayenne,150000,petrol,porsche,no
88001,16900,sedan,2006.0,manual,250.0,golf,125000,petrol,volkswagen,NaN
88290,11990,sedan,1991.0,manual,250.0,other,150000,petrol,audi,no
89165,16700,convertible,2001.0,manual,252.0,boxster,125000,petrol,porsche,no
90159,7999,wagon,2001.0,auto,250.0,a6,150000,lpg,audi,no
90414,0,sedan,2008.0,auto,250.0,golf,125000,petrol,volkswagen,no
90646,0,sedan,2001.0,manual,250.0,a6,150000,NaN,audi,no
91916,15900,convertible,2002.0,manual,252.0,boxster,80000,petrol,porsche,no
92258,17450,sedan,2012.0,manual,250.0,focus,70000,petrol,ford,no
92403,19800,sedan,2012.0,manual,250.0,focus,40000,petrol,ford,no
92716,14800,sedan,2006.0,manual,250.0,golf,150000,petrol,volkswagen,no
92780,9400,sedan,2005.0,auto,250.0,a3,125000,petrol,audi,no
92842,9900,sedan,2002.0,manual,250.0,156,125000,petrol,alfa_romeo,no
93969,4700,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,yes
94214,0,sedan,2001.0,manual,250.0,a6,150000,petrol,audi,no
94262,4000,wagon,1998.0,manual,250.0,3er,150000,petrol,bmw,NaN
94465,5600,sedan,2005.0,manual,250.0,golf,150000,petrol,volkswagen,NaN
94980,8000,sedan,2004.0,manual,250.0,a3,150000,petrol,audi,no
95029,10900,suv,2004.0,auto,250.0,cayenne,150000,petrol,porsche,no
95364,1850,sedan,1989.0,auto,250.0,100,150000,petrol,audi,yes
95386,16599,sedan,2011.0,manual,250.0,golf,70000,petrol,volkswagen,NaN
95522,6800,sedan,2002.0,manual,250.0,156,125000,petrol,alfa_romeo,no
96668,12999,coupe,2006.0,manual,250.0,golf,125000,petrol,volkswagen,no
98500,18000,suv,2004.0,auto,250.0,NaN,150000,lpg,porsche,no
98819,16890,wagon,2010.0,manual,250.0,159,70000,petrol,alfa_romeo,no
99018,9999,wagon,2005.0,manual,252.0,a4,150000,gasoline,audi,no
99109,9999,wagon,2007.0,auto,250.0,passat,90000,petrol,volkswagen,no
99122,0,other,2000.0,manual,250.0,NaN,100000,NaN,sonstige_autos,yes
99158,12000,suv,2009.0,auto,250.0,other,125000,petrol,saab,no
99396,6800,NaN,2016.0,manual,250.0,a3,125000,NaN,audi,NaN
99769,5000,sedan,2001.0,manual,250.0,a6,150000,petrol,audi,no
99916,850,sedan,1991.0,auto,250.0,other,150000,petrol,audi,NaN
100015,3799,wagon,2001.0,auto,250.0,other,150000,petrol,audi,no
100185,12990,coupe,1992.0,manual,250.0,NaN,150000,petrol,sonstige_autos,no
100244,17250,suv,2006.0,manual,250.0,cayenne,150000,petrol,porsche,no
100429,17500,sedan,2012.0,manual,250.0,focus,50000,petrol,ford,no
100640,14990,coupe,2011.0,manual,250.0,megane,60000,petrol,renault,no
101131,9800,convertible,2007.0,auto,250.0,eos,125000,petrol,volkswagen,no
101388,9499,wagon,2005.0,manual,252.0,a4,150000,gasoline,audi,no
101646,15500,coupe,2007.0,auto,250.0,golf,150000,petrol,volkswagen,no
102096,15800,coupe,1990.0,auto,252.0,other,150000,petrol,mercedes_benz,no
102176,8500,wagon,2006.0,auto,250.0,passat,90000,NaN,volkswagen,NaN
102256,5500,wagon,2002.0,manual,250.0,other,150000,petrol,audi,no
102401,4200,suv,2002.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
102841,18500,coupe,2008.0,NaN,250.0,tt,150000,petrol,audi,no
102952,5500,suv,2005.0,auto,250.0,cayenne,150000,lpg,porsche,yes
103150,19500,coupe,2008.0,auto,250.0,tt,80000,petrol,audi,NaN
104262,4650,wagon,1992.0,manual,250.0,other,150000,petrol,audi,no
104510,15500,sedan,2006.0,manual,250.0,golf,80000,petrol,volkswagen,no
104887,6250,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
105334,800,sedan,2001.0,auto,252.0,other,150000,petrol,chrysler,yes
106537,14750,coupe,2011.0,manual,250.0,megane,70000,petrol,renault,no
108111,3999,convertible,2001.0,auto,252.0,boxster,150000,petrol,porsche,NaN
108433,7500,suv,2004.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
108592,10000,sedan,1990.0,auto,252.0,other,150000,petrol,mercedes_benz,no
108944,1200,suv,NaN,auto,250.0,other,150000,petrol,chevrolet,no
109170,11990,sedan,2006.0,manual,250.0,a4,125000,petrol,audi,NaN
110220,9750,wagon,2008.0,auto,250.0,vectra,70000,petrol,opel,no
110374,14999,wagon,2009.0,auto,250.0,passat,125000,petrol,volkswagen,no
110440,7500,coupe,2003.0,auto,250.0,tt,150000,petrol,audi,no
110469,7500,wagon,2001.0,auto,250.0,other,150000,lpg,audi,no
113825,1699,wagon,2001.0,auto,250.0,v70,150000,petrol,volvo,no
114775,14500,convertible,2010.0,manual,250.0,cooper,90000,petrol,mini,no
116109,7500,suv,2005.0,auto,250.0,m_klasse,150000,gasoline,mercedes_benz,no
116653,12900,sedan,2006.0,auto,250.0,passat,125000,petrol,volkswagen,no
116867,14600,coupe,2006.0,auto,250.0,NaN,125000,petrol,audi,NaN
117230,1500,wagon,2008.0,auto,253.0,other,150000,petrol,chrysler,yes
117381,13990,coupe,2011.0,manual,250.0,megane,90000,petrol,renault,no
117651,14240,coupe,1990.0,auto,252.0,other,150000,petrol,mercedes_benz,no
117859,11000,coupe,2004.0,auto,250.0,tt,150000,petrol,audi,no
118096,17499,sedan,2013.0,manual,250.0,focus,30000,petrol,ford,no
118533,4000,sedan,1999.0,auto,252.0,7er,150000,gasoline,bmw,NaN
119089,11950,convertible,2001.0,manual,252.0,boxster,125000,petrol,porsche,no
119236,8600,suv,2004.0,auto,250.0,cayenne,150000,petrol,porsche,no
119396,19900,convertible,NaN,auto,250.0,other,100000,petrol,ford,no
120874,5800,NaN,2016.0,auto,250.0,5er,5000,NaN,bmw,no
120903,4000,small,2004.0,manual,250.0,a3,150000,petrol,audi,no
121530,9000,sedan,2006.0,auto,250.0,passat,125000,petrol,volkswagen,no
121957,15000,other,2002.0,auto,250.0,NaN,150000,petrol,chrysler,no
122044,13550,wagon,2007.0,auto,250.0,a3,90000,petrol,audi,no
122202,14500,coupe,2010.0,manual,250.0,megane,80000,petrol,renault,no
122509,10200,convertible,2004.0,auto,250.0,a4,150000,petrol,audi,no
122667,19900,coupe,1996.0,auto,250.0,other,150000,petrol,chevrolet,NaN
123343,13800,convertible,2000.0,manual,252.0,boxster,125000,petrol,porsche,no
123373,15900,wagon,2008.0,auto,250.0,5er,40000,gasoline,bmw,no
124468,17900,sedan,2012.0,manual,250.0,insignia,70000,petrol,opel,no

Аномальных значений больше нет.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 309329 entries, 0 to 354368
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Price             309329 non-null  int64
 1   VehicleType       274770 non-null  object
 2   RegistrationYear  303327 non-null  float64
 3   Gearbox           292122 non-null  object
 4   Power             302599 non-null  float64
 5   Model             290968 non-null  object
 6   Kilometer         309329 non-null  int64
 7   FuelType          278565 non-null  object
 8   Brand             309329 non-null  object
 9   NotRepaired       244771 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 26.0+ MB

Изучим столбцы с категориальными данными.

In [13]:
cat_features = ['VehicleType','Gearbox','Model','FuelType','Brand','NotRepaired']
for columns in cat_features:
    print(df[columns].value_counts(normalize=True))

sedan          0.284624
small          0.245835
wagon          0.205142
bus            0.094006
convertible    0.066219
coupe          0.053463
suv            0.039218
other          0.011493
Name: VehicleType, dtype: float64
manual    0.796838
auto      0.203162
Name: Gearbox, dtype: float64
golf                  0.081243
other                 0.078820
3er                   0.057395
polo                  0.036066
corsa                 0.033468
astra                 0.032251
passat                0.028556
a4                    0.028415
c_klasse              0.024577
5er                   0.022948
e_klasse              0.020645
a3                    0.018002
focus                 0.017627
fiesta                0.017373
a6                    0.016648
transporter           0.014730
2_reihe               0.014345
twingo                0.013768
fortwo                0.013665
a_klasse              0.013022
vectra                0.012819
mondeo                0.010847
3_reihe               0.010747
clio                  0.010647
1er                   0.010530
punto                 0.009819
touran                0.009781
megane                0.009132
zafira                0.008898
ibiza                 0.008296
ka                    0.008176
lupo                  0.006880
fabia                 0.006472
octavia               0.006417
cooper                0.006008
clk                   0.005739
micra                 0.005344
caddy                 0.005056
80                    0.004856
x_reihe               0.004812
scenic                0.004475
omega                 0.004406
civic                 0.004303
laguna                0.004269
sharan                0.004141
leon                  0.004066
6_reihe               0.003994
1_reihe               0.003983
i_reihe               0.003918
slk                   0.003818
galaxy                0.003629
meriva                0.003354
tt                    0.003334
yaris                 0.003182
mx_reihe              0.003121
kangoo                0.003110
7er                   0.003073
escort                0.002883
vito                  0.002853
500                   0.002846
m_klasse              0.002825
colt                  0.002791
b_klasse              0.002777
s_klasse              0.002736
one                   0.002736
bora                  0.002701
berlingo              0.002657
arosa                 0.002595
beetle                0.002557
sprinter              0.002533
transit               0.002495
v40                   0.002454
tigra                 0.002433
z_reihe               0.002289
fox                   0.002282
corolla               0.002189
c_max                 0.002182
swift                 0.002169
panda                 0.002100
seicento              0.002096
156                   0.001966
4_reihe               0.001949
tiguan                0.001949
v70                   0.001945
primera               0.001945
espace                0.001942
scirocco              0.001907
insignia              0.001883
stilo                 0.001873
almera                0.001825
a1                    0.001822
147                   0.001804
grand                 0.001794
avensis               0.001773
qashqai               0.001722
a8                    0.001663
touareg               0.001636
c3                    0.001636
a5                    0.001626
eos                   0.001595
c5                    0.001550
signum                0.001533
kaefer                0.001450
ducato                0.001423
c4                    0.001423
matiz                 0.001402
5_reihe               0.001395
agila                 0.001395
combo                 0.001358
601                   0.001354
aygo                  0.001344
100                   0.001303
cordoba               0.001289
getz                  0.001289
sl                    0.001285
carisma               0.001251
c2                    0.001227
c1                    0.001227
s_max                 0.001220
forfour               0.001220
kadett                0.001203
cuore                 0.001179
superb                0.001162
altea                 0.001162
jetta                 0.001151
picanto               0.001134
rav                   0.001127
a2                    0.001127
accord                0.001120
voyager               0.001117
cr_reihe              0.001117
rio                   0.001114
toledo                0.001100
alhambra              0.001076
doblo                 0.001069
sorento               0.001065
bravo                 0.001059
up                    0.001048
modus                 0.001031
logan                 0.001031
verso                 0.001010
ptcruiser             0.000979
jazz                  0.000976
santa                 0.000976
fusion                0.000962
sandero               0.000900
vivaro                0.000900
kuga                  0.000900
roomster              0.000870
carnival              0.000866
galant                0.000818
ceed                  0.000808
sportage              0.000797
v50                   0.000770
auris                 0.000756
xc_reihe              0.000742
cl                    0.000739
cayenne               0.000725
impreza               0.000718
calibra               0.000715
viano                 0.000715
freelander            0.000711
boxster               0.000708
tucson                0.000705
phaeton               0.000701
lancer                0.000698
jimny                 0.000691
159                   0.000677
pajero                0.000674
850                   0.000670
duster                0.000660
ypsilon               0.000650
x_trail               0.000636
spider                0.000629
c_reihe               0.000625
clubman               0.000591
x_type                0.000564
roadster              0.000560
mustang               0.000557
q7                    0.000553
cherokee              0.000546
yeti                  0.000546
captiva               0.000522
legacy                0.000516
6er                   0.000505
v_klasse              0.000485
justy                 0.000464
300c                  0.000461
s60                   0.000450
cc                    0.000443
sirion                0.000440
rx_reihe              0.000440
forester              0.000436
m_reihe               0.000423
s_type                0.000423
note                  0.000419
spark                 0.000412
r19                   0.000412
niva                  0.000406
outlander             0.000399
900                   0.000368
aveo                  0.000368
antara                0.000340
90                    0.000340
wrangler              0.000340
juke                  0.000333
g_klasse              0.000330
exeo                  0.000320
kalos                 0.000302
lanos                 0.000299
navara                0.000292
citigo                0.000278
911                   0.000265
discovery             0.000244
range_rover           0.000241
defender              0.000241
q5                    0.000234
mii                   0.000223
cx_reihe              0.000220
glk                   0.000210
nubira                0.000203
move                  0.000199
crossfire             0.000192
lybra                 0.000182
range_rover_sport     0.000168
145                   0.000165
croma                 0.000148
v60                   0.000134
delta                 0.000120
terios                0.000117
lodgy                 0.000110
9000                  0.000096
charade               0.000086
b_max                 0.000079
musa                  0.000079
materia               0.000062
200                   0.000058
kappa                 0.000052
q3                    0.000048
samara                0.000045
amarok                0.000045
gl                    0.000041
elefantino            0.000038
serie_2               0.000027
i3                    0.000027
kalina                0.000024
rangerover            0.000014
serie_3               0.000014
serie_1               0.000007
range_rover_evoque    0.000003
Name: Model, dtype: float64
petrol      0.674342
gasoline    0.304396
lpg         0.017547
cng         0.001881
hybrid      0.000797
other       0.000718
electric    0.000319
Name: FuelType, dtype: float64
volkswagen        0.206599
opel              0.109776
bmw               0.102532
mercedes_benz     0.092769
audi              0.082340
ford              0.072415
renault           0.051072
peugeot           0.031707
fiat              0.028045
seat              0.020005
mazda             0.016529
skoda             0.016057
smart             0.015592
citroen           0.015511
nissan            0.014512
toyota            0.013733
hyundai           0.010652
sonstige_autos    0.009475
volvo             0.009398
mini              0.009265
mitsubishi        0.009091
honda             0.008525
kia               0.007264
suzuki            0.006976
alfa_romeo        0.006925
chevrolet         0.005328
chrysler          0.004371
dacia             0.002683
daihatsu          0.002431
subaru            0.002347
porsche           0.002260
jeep              0.002066
trabant           0.001794
daewoo            0.001642
land_rover        0.001639
saab              0.001565
jaguar            0.001549
rover             0.001452
lancia            0.001432
lada              0.000679
Name: Brand, dtype: float64
no     0.86337
yes    0.13663
Name: NotRepaired, dtype: float64

C категориальными данными все в порядке.

Изучим пропускки в датафрейме.

In [14]:
df.isna().sum()

Price                   0
VehicleType         34559
RegistrationYear     6002
Gearbox             17207
Power                6730
Model               18361
Kilometer               0
FuelType            30764
Brand                   0
NotRepaired         64558
dtype: int64

Видим, что есть пропуски во всех столбцах, кроме Price, Brand, Kilometer.

Посмотрим на соотношение значений в столбце NotRepaired.

In [15]:
df['NotRepaired'].value_counts(normalize=True)

no     0.86337
yes    0.13663
Name: NotRepaired, dtype: float64

Видно, что большинство машин не было в ремонте. Значит скорее всего пропущенные значения в столбце NotRepaired означают, что машина не ремонтировалась.

In [16]:
df['NotRepaired'] = df['NotRepaired'].fillna('no')

Остальные пропуски в столбцах c категориальными данными заполним значением 'other'.

In [17]:
df['FuelType'] = df['FuelType'].fillna('other')

In [18]:
df['Gearbox'] = df['Gearbox'].fillna('other')

In [19]:
df['VehicleType'] = df['VehicleType'].fillna('other')

In [20]:
df['Model'] = df['Model'].fillna('other')

Посмотрим на пропуски в столбцах c численными данными. Проанализируем матрицу корреляции.

In [21]:
df.corr()

                     Price  RegistrationYear     Power  Kilometer
Price             1.000000          0.458858  0.449806  -0.325592
RegistrationYear  0.458858          1.000000  0.081080  -0.279207
Power             0.449806          0.081080  1.000000   0.100225
Kilometer        -0.325592         -0.279207  0.100225   1.000000

Заполним пропуски в столбце RegistrationYear на медианное значение, сгруппированое по столбцу Price.

In [22]:
df['RegistrationYear'] = df.groupby(['Price'])['RegistrationYear'].apply(lambda x: x.fillna(x.median()))
df['RegistrationYear'].fillna(df['RegistrationYear'].median(), inplace=True)

Заполним пропуски в столбце Power на медианное значение, сгруппированое по столбцу Price.

In [23]:
df['Power'] = df.groupby(['Price'])['Power'].apply(lambda x: x.fillna(x.median()))
df['Power'].fillna(df['Power'].median(), inplace=True)

Посчитаем пропущенные значения снова.

In [24]:
df.isna().sum()

Price               0
VehicleType         0
RegistrationYear    0
Gearbox             0
Power               0
Model               0
Kilometer           0
FuelType            0
Brand               0
NotRepaired         0
dtype: int64

Произведем кодирование категориальных данных с помощью LabelEncoder

In [26]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
cat_features = ['VehicleType','Gearbox','Model','FuelType','Brand','NotRepaired']
label_encode = LabelEncoder()
for column in cat_features:
    label_encode.fit(df[column].astype('str'))
    df[column] = label_encode.transform(df[column].astype('str'))

Разделим данные на обучающую, валидационную выборки. Определим признаки.

In [27]:
df_train, df_test = train_test_split(df, test_size=0.4, random_state=12345)
df_test, df_valid = train_test_split(df_test, test_size=0.5, random_state=12345)

features_valid = df_valid.drop(['Price'], axis=1)
target_valid = df_valid['Price']
features_train = df_train.drop(['Price'], axis=1)
target_train = df_train['Price']
features_test = df_test.drop(['Price'], axis=1)
target_test = df_test['Price']
features = df.drop('Price', axis=1)
target = df['Price']

Масштабируем данные с помощью функции.

In [28]:
def scale_to_standard(train, test, valid):
    scaler = StandardScaler()
    numeric = ['RegistrationYear','Power','Kilometer']   
    scaler.fit(train[numeric])
    train[numeric] = scaler.transform(train[numeric])
    valid[numeric]=scaler.transform(valid[numeric])
    test[numeric] = scaler.transform(test[numeric])
scale_to_standard(features_train, features_valid, features_test)

# Вывод

На данном шаге:

- Импортировали библиотеки.
- Открыли файл и изучили данные.
- Провели предобработку данных.
- Пропущенные значения заполнили.
- Аномальные значения удалили.
- Произвели кодирование категориальных данных 
- Разделили данные на обучающую, валидационную выборки. 
- Масштабировали данные.

## Обучение моделей

На данном этапе:
- обучим разные модели. 
- подберем гиперпараметры.

Подберем лучшие параметры для модели RandomForestRegressor с помощью функции GridSearchCV

In [29]:
rfr = RandomForestRegressor()
parametrs = { 'n_estimators': range (10, 51, 10),
             'max_depth': range (1,13, 2)}
grid = GridSearchCV(rfr, parametrs, scoring='neg_mean_squared_error')
grid.fit(features_train,target_train)
print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 11, 'n_estimators': 50}
-4084252.055419804

Подберем лучшие параметры для модели CatBoostRegressor с помощью функции GridSearchCV

In [30]:
cbr = CatBoostRegressor()
parametrs = {'depth': range (1,10, 2)}
grid = GridSearchCV(cbr, parametrs, scoring='neg_mean_squared_error')
grid.fit(features_train,target_train, cat_features=cat_features)
print(grid.best_params_)
print(grid.best_score_)

Learning rate set to 0.09022
0:	learn: 4443.2898998	total: 81.9ms	remaining: 1m 21s
1:	learn: 4337.4755917	total: 114ms	remaining: 56.8s
2:	learn: 4247.9045133	total: 135ms	remaining: 45s
3:	learn: 4167.2910526	total: 167ms	remaining: 41.6s
4:	learn: 4090.6923938	total: 186ms	remaining: 37.1s
5:	learn: 4023.2043713	total: 206ms	remaining: 34.1s
6:	learn: 3959.1796527	total: 225ms	remaining: 31.9s
7:	learn: 3902.7580587	total: 245ms	remaining: 30.3s
8:	learn: 3846.9006209	total: 263ms	remaining: 29s
9:	learn: 3798.1533961	total: 281ms	remaining: 27.8s
10:	learn: 3750.7853368	total: 301ms	remaining: 27.1s
11:	learn: 3709.1245713	total: 320ms	remaining: 26.3s
12:	learn: 3668.8076936	total: 339ms	remaining: 25.8s
13:	learn: 3631.4016378	total: 359ms	remaining: 25.3s
14:	learn: 3595.7143184	total: 383ms	remaining: 25.1s
15:	learn: 3564.0340842	total: 402ms	remaining: 24.7s
16:	learn: 3533.0833579	total: 421ms	remaining: 24.3s
17:	learn: 3503.6248261	total: 441ms	remaining: 24s
18:	learn: 3475.4908456	total: 460ms	remaining: 23.7s
19:	learn: 3449.9900328	total: 479ms	remaining: 23.5s
20:	learn: 3424.1962077	total: 498ms	remaining: 23.2s
21:	learn: 3399.3870087	total: 519ms	remaining: 23.1s
22:	learn: 3375.8651723	total: 544ms	remaining: 23.1s
23:	learn: 3354.0685606	total: 570ms	remaining: 23.2s
24:	learn: 3332.1970381	total: 595ms	remaining: 23.2s
25:	learn: 3311.7998119	total: 620ms	remaining: 23.2s
26:	learn: 3291.7673287	total: 645ms	remaining: 23.3s
27:	learn: 3270.6100155	total: 672ms	remaining: 23.3s
28:	learn: 3251.3516931	total: 698ms	remaining: 23.4s
29:	learn: 3232.0415525	total: 725ms	remaining: 23.4s
30:	learn: 3214.4100277	total: 751ms	remaining: 23.5s
31:	learn: 3197.6924439	total: 777ms	remaining: 23.5s
32:	learn: 3180.1974706	total: 804ms	remaining: 23.6s
33:	learn: 3164.0754714	total: 831ms	remaining: 23.6s
34:	learn: 3148.9556704	total: 859ms	remaining: 23.7s
35:	learn: 3133.8928384	total: 887ms	remaining: 23.7s
36:	learn: 3119.6771682	total: 914ms	remaining: 23.8s
37:	learn: 3105.5459474	total: 943ms	remaining: 23.9s
38:	learn: 3090.7396071	total: 971ms	remaining: 23.9s
39:	learn: 3074.8209894	total: 1000ms	remaining: 24s
40:	learn: 3061.5824319	total: 1.02s	remaining: 24s
41:	learn: 3047.9771896	total: 1.05s	remaining: 24s
42:	learn: 3035.3567137	total: 1.08s	remaining: 24s
43:	learn: 3021.8074791	total: 1.11s	remaining: 24s
44:	learn: 3010.2535028	total: 1.13s	remaining: 24s
45:	learn: 2997.9433266	total: 1.16s	remaining: 24.1s
46:	learn: 2975.2271829	total: 1.19s	remaining: 24.1s
47:	learn: 2956.9031967	total: 1.22s	remaining: 24.1s
48:	learn: 2940.3032669	total: 1.24s	remaining: 24.1s
49:	learn: 2926.1676530	total: 1.27s	remaining: 24.1s
50:	learn: 2913.7824493	total: 1.29s	remaining: 24.1s
51:	learn: 2902.9863170	total: 1.32s	remaining: 24s
52:	learn: 2892.0688876	total: 1.35s	remaining: 24.1s
53:	learn: 2881.4304143	total: 1.38s	remaining: 24.1s
54:	learn: 2871.3707526	total: 1.4s	remaining: 24.1s
55:	learn: 2861.5187649	total: 1.43s	remaining: 24s
56:	learn: 2852.5451038	total: 1.45s	remaining: 24s
57:	learn: 2843.4312379	total: 1.48s	remaining: 24s
58:	learn: 2834.4418061	total: 1.5s	remaining: 23.9s
59:	learn: 2826.0477722	total: 1.52s	remaining: 23.9s
60:	learn: 2817.6846358	total: 1.55s	remaining: 23.9s
61:	learn: 2809.4882537	total: 1.58s	remaining: 23.9s
62:	learn: 2801.9740859	total: 1.6s	remaining: 23.8s
63:	learn: 2794.4440526	total: 1.63s	remaining: 23.8s
64:	learn: 2787.4935656	total: 1.65s	remaining: 23.8s
65:	learn: 2780.1082134	total: 1.68s	remaining: 23.8s
66:	learn: 2772.9715380	total: 1.71s	remaining: 23.8s
67:	learn: 2765.5111747	total: 1.73s	remaining: 23.8s
68:	learn: 2758.9438537	total: 1.76s	remaining: 23.8s
69:	learn: 2751.9144553	total: 1.79s	remaining: 23.8s
70:	learn: 2745.5743255	total: 1.82s	remaining: 23.8s
71:	learn: 2739.1417030	total: 1.85s	remaining: 23.8s
72:	learn: 2732.7514141	total: 1.88s	remaining: 23.9s
73:	learn: 2725.7544832	total: 1.91s	remaining: 23.9s
74:	learn: 2719.7586369	total: 1.93s	remaining: 23.9s
75:	learn: 2713.4121382	total: 1.96s	remaining: 23.9s
76:	learn: 2708.0050045	total: 1.99s	remaining: 23.9s
77:	learn: 2702.4257140	total: 2.02s	remaining: 23.9s
78:	learn: 2696.9933474	total: 2.05s	remaining: 23.9s
79:	learn: 2691.3624728	total: 2.08s	remaining: 23.9s
80:	learn: 2685.3606228	total: 2.1s	remaining: 23.8s
81:	learn: 2680.0817026	total: 2.13s	remaining: 23.8s
82:	learn: 2674.5223049	total: 2.15s	remaining: 23.8s
83:	learn: 2669.6413343	total: 2.18s	remaining: 23.7s
84:	learn: 2664.5645769	total: 2.2s	remaining: 23.7s
85:	learn: 2659.7062495	total: 2.23s	remaining: 23.7s
86:	learn: 2654.6035528	total: 2.25s	remaining: 23.6s
87:	learn: 2649.7517120	total: 2.28s	remaining: 23.6s
88:	learn: 2645.4378359	total: 2.3s	remaining: 23.6s
89:	learn: 2640.8302210	total: 2.33s	remaining: 23.5s
90:	learn: 2636.1834874	total: 2.35s	remaining: 23.5s
91:	learn: 2632.0142872	total: 2.38s	remaining: 23.5s
92:	learn: 2627.8609341	total: 2.4s	remaining: 23.4s
93:	learn: 2623.8288004	total: 2.43s	remaining: 23.4s
94:	learn: 2619.7921940	total: 2.45s	remaining: 23.4s
95:	learn: 2615.5800560	total: 2.48s	remaining: 23.4s
96:	learn: 2611.6107293	total: 2.5s	remaining: 23.3s
97:	learn: 2607.9647897	total: 2.53s	remaining: 23.3s
98:	learn: 2604.0219535	total: 2.56s	remaining: 23.3s
99:	learn: 2600.1583519	total: 2.59s	remaining: 23.3s
100:	learn: 2596.5397760	total: 2.62s	remaining: 23.3s
101:	learn: 2592.9568083	total: 2.64s	remaining: 23.2s
102:	learn: 2589.3341962	total: 2.67s	remaining: 23.2s
103:	learn: 2586.5649163	total: 2.69s	remaining: 23.2s
104:	learn: 2583.0534812	total: 2.72s	remaining: 23.2s
105:	learn: 2579.4768901	total: 2.74s	remaining: 23.1s
106:	learn: 2576.2081104	total: 2.77s	remaining: 23.1s
107:	learn: 2572.8932950	total: 2.79s	remaining: 23.1s
108:	learn: 2569.8187114	total: 2.82s	remaining: 23.1s
109:	learn: 2566.8043401	total: 2.85s	remaining: 23s
110:	learn: 2563.7276249	total: 2.87s	remaining: 23s
111:	learn: 2560.1773507	total: 2.9s	remaining: 23s
112:	learn: 2557.3484929	total: 2.92s	remaining: 22.9s
113:	learn: 2554.4789455	total: 2.95s	remaining: 22.9s
114:	learn: 2551.5689386	total: 2.97s	remaining: 22.9s
115:	learn: 2548.7638053	total: 3s	remaining: 22.9s
116:	learn: 2545.7654789	total: 3.02s	remaining: 22.8s
117:	learn: 2542.9622019	total: 3.05s	remaining: 22.8s
118:	learn: 2540.3044053	total: 3.07s	remaining: 22.8s
119:	learn: 2537.7247608	total: 3.1s	remaining: 22.7s
120:	learn: 2535.1719146	total: 3.12s	remaining: 22.7s
121:	learn: 2532.6806396	total: 3.15s	remaining: 22.7s
122:	learn: 2530.5178632	total: 3.17s	remaining: 22.6s
123:	learn: 2528.1599895	total: 3.19s	remaining: 22.5s
124:	learn: 2525.5835310	total: 3.2s	remaining: 22.4s
125:	learn: 2523.2046912	total: 3.22s	remaining: 22.4s
126:	learn: 2520.9002338	total: 3.24s	remaining: 22.3s
127:	learn: 2518.6266322	total: 3.26s	remaining: 22.2s
128:	learn: 2516.1857957	total: 3.27s	remaining: 22.1s
129:	learn: 2513.9857679	total: 3.29s	remaining: 22s
130:	learn: 2512.1673557	total: 3.31s	remaining: 22s
131:	learn: 2510.0677263	total: 3.33s	remaining: 21.9s
132:	learn: 2507.7828411	total: 3.35s	remaining: 21.8s
133:	learn: 2506.2317146	total: 3.36s	remaining: 21.7s
134:	learn: 2504.2002405	total: 3.38s	remaining: 21.7s
135:	learn: 2502.2782992	total: 3.4s	remaining: 21.6s
136:	learn: 2500.1723861	total: 3.42s	remaining: 21.5s
137:	learn: 2498.3557998	total: 3.44s	remaining: 21.5s
138:	learn: 2496.5642136	total: 3.45s	remaining: 21.4s
139:	learn: 2494.7358666	total: 3.47s	remaining: 21.3s
140:	learn: 2492.9573763	total: 3.49s	remaining: 21.3s
141:	learn: 2491.3074957	total: 3.51s	remaining: 21.2s
142:	learn: 2489.5425619	total: 3.52s	remaining: 21.1s
143:	learn: 2487.6828896	total: 3.54s	remaining: 21.1s
144:	learn: 2485.9443006	total: 3.56s	remaining: 21s
145:	learn: 2484.3292689	total: 3.58s	remaining: 20.9s
146:	learn: 2482.7025548	total: 3.6s	remaining: 20.9s
147:	learn: 2480.9000392	total: 3.62s	remaining: 20.8s
148:	learn: 2479.3693984	total: 3.64s	remaining: 20.8s
149:	learn: 2477.6853677	total: 3.65s	remaining: 20.7s
150:	learn: 2476.2139777	total: 3.68s	remaining: 20.7s
151:	learn: 2474.7029477	total: 3.69s	remaining: 20.6s
152:	learn: 2473.3050641	total: 3.71s	remaining: 20.6s
153:	learn: 2471.8212470	total: 3.73s	remaining: 20.5s
154:	learn: 2470.2898676	total: 3.75s	remaining: 20.4s
155:	learn: 2468.8759786	total: 3.77s	remaining: 20.4s
156:	learn: 2467.4646008	total: 3.79s	remaining: 20.3s
157:	learn: 2466.0975964	total: 3.81s	remaining: 20.3s
158:	learn: 2464.7719346	total: 3.82s	remaining: 20.2s
159:	learn: 2463.2913988	total: 3.84s	remaining: 20.2s
160:	learn: 2462.0017400	total: 3.86s	remaining: 20.1s
161:	learn: 2460.7341144	total: 3.88s	remaining: 20.1s
162:	learn: 2459.3555761	total: 3.9s	remaining: 20s
163:	learn: 2458.0467097	total: 3.92s	remaining: 20s
164:	learn: 2456.8296146	total: 3.94s	remaining: 19.9s
165:	learn: 2455.7708172	total: 3.95s	remaining: 19.9s
166:	learn: 2454.5687203	total: 3.97s	remaining: 19.8s
167:	learn: 2453.3818000	total: 3.99s	remaining: 19.8s
168:	learn: 2452.1254191	total: 4.01s	remaining: 19.7s
169:	learn: 2451.0050952	total: 4.03s	remaining: 19.7s
170:	learn: 2449.8787523	total: 4.05s	remaining: 19.6s
171:	learn: 2448.7110588	total: 4.07s	remaining: 19.6s
172:	learn: 2447.8994465	total: 4.09s	remaining: 19.5s
173:	learn: 2446.8725610	total: 4.1s	remaining: 19.5s
174:	learn: 2445.8045330	total: 4.12s	remaining: 19.4s
175:	learn: 2444.7169904	total: 4.14s	remaining: 19.4s
176:	learn: 2443.6741723	total: 4.16s	remaining: 19.4s
177:	learn: 2442.5575801	total: 4.18s	remaining: 19.3s
178:	learn: 2441.5282553	total: 4.2s	remaining: 19.3s
179:	learn: 2440.5358154	total: 4.22s	remaining: 19.2s
180:	learn: 2439.5466652	total: 4.24s	remaining: 19.2s
181:	learn: 2438.5346350	total: 4.25s	remaining: 19.1s
182:	learn: 2437.6316600	total: 4.27s	remaining: 19.1s
183:	learn: 2436.6956167	total: 4.29s	remaining: 19s
184:	learn: 2435.6772438	total: 4.31s	remaining: 19s
185:	learn: 2434.7065782	total: 4.33s	remaining: 18.9s
186:	learn: 2433.8038847	total: 4.34s	remaining: 18.9s
187:	learn: 2432.9108955	total: 4.36s	remaining: 18.8s
188:	learn: 2431.9686156	total: 4.38s	remaining: 18.8s
189:	learn: 2431.0947345	total: 4.4s	remaining: 18.8s
190:	learn: 2430.4230684	total: 4.42s	remaining: 18.7s
191:	learn: 2429.5749353	total: 4.44s	remaining: 18.7s
192:	learn: 2428.6980174	total: 4.46s	remaining: 18.6s
193:	learn: 2427.8715407	total: 4.48s	remaining: 18.6s
194:	learn: 2427.0636616	total: 4.5s	remaining: 18.6s
195:	learn: 2426.2450990	total: 4.52s	remaining: 18.5s
196:	learn: 2425.4547459	total: 4.53s	remaining: 18.5s
197:	learn: 2424.6105254	total: 4.55s	remaining: 18.4s
198:	learn: 2423.9361226	total: 4.57s	remaining: 18.4s
199:	learn: 2423.1698452	total: 4.59s	remaining: 18.4s
200:	learn: 2422.4153168	total: 4.61s	remaining: 18.3s
201:	learn: 2421.6668254	total: 4.63s	remaining: 18.3s
202:	learn: 2420.9749420	total: 4.65s	remaining: 18.2s
203:	learn: 2420.2092890	total: 4.66s	remaining: 18.2s
204:	learn: 2419.4762969	total: 4.68s	remaining: 18.2s
205:	learn: 2418.7323346	total: 4.7s	remaining: 18.1s
206:	learn: 2418.0104472	total: 4.72s	remaining: 18.1s
207:	learn: 2417.3179646	total: 4.74s	remaining: 18s
208:	learn: 2416.6216884	total: 4.76s	remaining: 18s
209:	learn: 2415.9382208	total: 4.77s	remaining: 18s
210:	learn: 2415.4866371	total: 4.79s	remaining: 17.9s
211:	learn: 2414.8194799	total: 4.81s	remaining: 17.9s
212:	learn: 2414.2265286	total: 4.83s	remaining: 17.8s
213:	learn: 2413.5440024	total: 4.84s	remaining: 17.8s
214:	learn: 2412.8850659	total: 4.86s	remaining: 17.8s
215:	learn: 2412.2319994	total: 4.88s	remaining: 17.7s
216:	learn: 2411.6024148	total: 4.9s	remaining: 17.7s
217:	learn: 2410.9893430	total: 4.92s	remaining: 17.6s
218:	learn: 2410.3808640	total: 4.94s	remaining: 17.6s
219:	learn: 2409.7726576	total: 4.96s	remaining: 17.6s
220:	learn: 2409.2206609	total: 4.98s	remaining: 17.5s
221:	learn: 2408.6088673	total: 5s	remaining: 17.5s
222:	learn: 2408.0324672	total: 5.02s	remaining: 17.5s
223:	learn: 2407.4679249	total: 5.04s	remaining: 17.4s
224:	learn: 2406.8981767	total: 5.05s	remaining: 17.4s
225:	learn: 2406.3570361	total: 5.07s	remaining: 17.4s
226:	learn: 2405.8213589	total: 5.09s	remaining: 17.3s
227:	learn: 2405.3770574	total: 5.11s	remaining: 17.3s
228:	learn: 2404.8166395	total: 5.13s	remaining: 17.3s
229:	learn: 2404.2774166	total: 5.14s	remaining: 17.2s
230:	learn: 2403.7605835	total: 5.16s	remaining: 17.2s
231:	learn: 2403.2469861	total: 5.18s	remaining: 17.1s
232:	learn: 2402.7150702	total: 5.2s	remaining: 17.1s
233:	learn: 2402.2047093	total: 5.21s	remaining: 17.1s
234:	learn: 2401.7567298	total: 5.23s	remaining: 17s
235:	learn: 2401.2615337	total: 5.25s	remaining: 17s
236:	learn: 2400.7386076	total: 5.27s	remaining: 17s
237:	learn: 2400.2737271	total: 5.29s	remaining: 16.9s
238:	learn: 2399.8004103	total: 5.3s	remaining: 16.9s
239:	learn: 2399.3401390	total: 5.33s	remaining: 16.9s
240:	learn: 2398.8602024	total: 5.34s	remaining: 16.8s
241:	learn: 2398.5519140	total: 5.36s	remaining: 16.8s
242:	learn: 2398.0996346	total: 5.38s	remaining: 16.8s
243:	learn: 2397.6565371	total: 5.4s	remaining: 16.7s
244:	learn: 2397.2091826	total: 5.41s	remaining: 16.7s
245:	learn: 2396.7769308	total: 5.43s	remaining: 16.7s
246:	learn: 2396.3527620	total: 5.45s	remaining: 16.6s
247:	learn: 2395.9473496	total: 5.47s	remaining: 16.6s
248:	learn: 2395.5389797	total: 5.49s	remaining: 16.6s
249:	learn: 2395.1230696	total: 5.5s	remaining: 16.5s
250:	learn: 2394.7052437	total: 5.52s	remaining: 16.5s
251:	learn: 2394.3051720	total: 5.54s	remaining: 16.4s
252:	learn: 2393.9115800	total: 5.56s	remaining: 16.4s
253:	learn: 2393.5540517	total: 5.58s	remaining: 16.4s
254:	learn: 2393.1636077	total: 5.59s	remaining: 16.3s
255:	learn: 2392.7563095	total: 5.61s	remaining: 16.3s
256:	learn: 2392.3549070	total: 5.63s	remaining: 16.3s
257:	learn: 2391.9760261	total: 5.65s	remaining: 16.2s
258:	learn: 2391.6149612	total: 5.67s	remaining: 16.2s
259:	learn: 2391.2440702	total: 5.68s	remaining: 16.2s
260:	learn: 2390.8727961	total: 5.7s	remaining: 16.1s
261:	learn: 2390.1321571	total: 5.73s	remaining: 16.1s
262:	learn: 2389.5159675	total: 5.74s	remaining: 16.1s
263:	learn: 2389.0058192	total: 5.76s	remaining: 16.1s
264:	learn: 2388.5613557	total: 5.78s	remaining: 16s
265:	learn: 2388.1934062	total: 5.8s	remaining: 16s
266:	learn: 2387.8259946	total: 5.82s	remaining: 16s
267:	learn: 2387.4820441	total: 5.83s	remaining: 15.9s
268:	learn: 2387.1399741	total: 5.85s	remaining: 15.9s
269:	learn: 2386.7847247	total: 5.87s	remaining: 15.9s
270:	learn: 2386.4432298	total: 5.89s	remaining: 15.8s
271:	learn: 2386.1104883	total: 5.91s	remaining: 15.8s
272:	learn: 2385.7748478	total: 5.93s	remaining: 15.8s
273:	learn: 2385.5573233	total: 5.95s	remaining: 15.8s
274:	learn: 2385.2072584	total: 5.97s	remaining: 15.7s
275:	learn: 2384.9684977	total: 5.99s	remaining: 15.7s
276:	learn: 2384.6437578	total: 6.01s	remaining: 15.7s
277:	learn: 2384.4637406	total: 6.03s	remaining: 15.7s
278:	learn: 2384.1429926	total: 6.04s	remaining: 15.6s
279:	learn: 2383.8267702	total: 6.07s	remaining: 15.6s
280:	learn: 2383.5130845	total: 6.08s	remaining: 15.6s
281:	learn: 2383.1996235	total: 6.1s	remaining: 15.5s
282:	learn: 2382.8909921	total: 6.12s	remaining: 15.5s
283:	learn: 2382.5801459	total: 6.14s	remaining: 15.5s
284:	learn: 2382.2586490	total: 6.16s	remaining: 15.5s
285:	learn: 2381.9570514	total: 6.18s	remaining: 15.4s
286:	learn: 2381.6547655	total: 6.2s	remaining: 15.4s
287:	learn: 2381.3606268	total: 6.22s	remaining: 15.4s
288:	learn: 2381.1773837	total: 6.24s	remaining: 15.4s
289:	learn: 2380.8958490	total: 6.26s	remaining: 15.3s
290:	learn: 2380.6099697	total: 6.28s	remaining: 15.3s
291:	learn: 2380.3293005	total: 6.3s	remaining: 15.3s
292:	learn: 2380.0579482	total: 6.31s	remaining: 15.2s
293:	learn: 2379.7933357	total: 6.33s	remaining: 15.2s
294:	learn: 2379.5308783	total: 6.35s	remaining: 15.2s
295:	learn: 2379.2590084	total: 6.37s	remaining: 15.2s
296:	learn: 2378.9951754	total: 6.39s	remaining: 15.1s
297:	learn: 2378.7350105	total: 6.41s	remaining: 15.1s
298:	learn: 2378.4822592	total: 6.43s	remaining: 15.1s
299:	learn: 2378.2332785	total: 6.45s	remaining: 15s
300:	learn: 2377.9779103	total: 6.46s	remaining: 15s
301:	learn: 2377.7940512	total: 6.49s	remaining: 15s
302:	learn: 2377.6607988	total: 6.5s	remaining: 15s
303:	learn: 2377.4043493	total: 6.53s	remaining: 15s
304:	learn: 2377.1682090	total: 6.56s	remaining: 14.9s
305:	learn: 2376.9265888	total: 6.58s	remaining: 14.9s
306:	learn: 2376.6854612	total: 6.61s	remaining: 14.9s
307:	learn: 2376.4474018	total: 6.63s	remaining: 14.9s
308:	learn: 2376.1989998	total: 6.66s	remaining: 14.9s
309:	learn: 2375.9306443	total: 6.68s	remaining: 14.9s
310:	learn: 2375.7043310	total: 6.71s	remaining: 14.9s
311:	learn: 2375.4690088	total: 6.73s	remaining: 14.9s
312:	learn: 2375.2440109	total: 6.76s	remaining: 14.8s
313:	learn: 2375.0182907	total: 6.78s	remaining: 14.8s
314:	learn: 2374.7998350	total: 6.81s	remaining: 14.8s
315:	learn: 2374.5776748	total: 6.84s	remaining: 14.8s
316:	learn: 2374.3563341	total: 6.87s	remaining: 14.8s
317:	learn: 2374.1404699	total: 6.89s	remaining: 14.8s
318:	learn: 2373.9233657	total: 6.92s	remaining: 14.8s
319:	learn: 2373.7027910	total: 6.95s	remaining: 14.8s
320:	learn: 2373.4646323	total: 6.97s	remaining: 14.7s
321:	learn: 2373.2572318	total: 7s	remaining: 14.7s
322:	learn: 2373.0517794	total: 7.02s	remaining: 14.7s
323:	learn: 2372.8510721	total: 7.05s	remaining: 14.7s
324:	learn: 2372.6484495	total: 7.07s	remaining: 14.7s
325:	learn: 2372.4392547	total: 7.1s	remaining: 14.7s
326:	learn: 2372.2320266	total: 7.13s	remaining: 14.7s
327:	learn: 2372.0309219	total: 7.15s	remaining: 14.7s
328:	learn: 2371.8698994	total: 7.18s	remaining: 14.6s
329:	learn: 2371.6701979	total: 7.2s	remaining: 14.6s
330:	learn: 2371.4609824	total: 7.22s	remaining: 14.6s
331:	learn: 2371.2626482	total: 7.25s	remaining: 14.6s
332:	learn: 2371.0681344	total: 7.27s	remaining: 14.6s
333:	learn: 2370.8782096	total: 7.3s	remaining: 14.6s
334:	learn: 2370.6920055	total: 7.32s	remaining: 14.5s
335:	learn: 2370.5177048	total: 7.34s	remaining: 14.5s
336:	learn: 2370.3434473	total: 7.37s	remaining: 14.5s
337:	learn: 2370.1656839	total: 7.39s	remaining: 14.5s
338:	learn: 2369.9873753	total: 7.42s	remaining: 14.5s
339:	learn: 2369.8033979	total: 7.45s	remaining: 14.5s
340:	learn: 2369.6230522	total: 7.47s	remaining: 14.4s
341:	learn: 2369.5035239	total: 7.49s	remaining: 14.4s
342:	learn: 2369.4019741	total: 7.52s	remaining: 14.4s
343:	learn: 2369.2274212	total: 7.54s	remaining: 14.4s
344:	learn: 2369.0746011	total: 7.57s	remaining: 14.4s
345:	learn: 2368.8971855	total: 7.59s	remaining: 14.4s
346:	learn: 2368.7309292	total: 7.62s	remaining: 14.3s
347:	learn: 2368.5619996	total: 7.65s	remaining: 14.3s
348:	learn: 2368.3920381	total: 7.67s	remaining: 14.3s
349:	learn: 2368.2202225	total: 7.7s	remaining: 14.3s
350:	learn: 2368.0525799	total: 7.72s	remaining: 14.3s
351:	learn: 2367.8841580	total: 7.75s	remaining: 14.3s
352:	learn: 2367.7705981	total: 7.77s	remaining: 14.2s
353:	learn: 2367.6023814	total: 7.8s	remaining: 14.2s
354:	learn: 2367.4391534	total: 7.82s	remaining: 14.2s
355:	learn: 2367.2812544	total: 7.85s	remaining: 14.2s
356:	learn: 2367.1278604	total: 7.88s	remaining: 14.2s
357:	learn: 2366.9597434	total: 7.9s	remaining: 14.2s
358:	learn: 2366.8241832	total: 7.93s	remaining: 14.2s
359:	learn: 2366.7362321	total: 7.96s	remaining: 14.1s
360:	learn: 2366.5782430	total: 7.99s	remaining: 14.1s
361:	learn: 2366.4014602	total: 8.01s	remaining: 14.1s
362:	learn: 2366.2468169	total: 8.04s	remaining: 14.1s
363:	learn: 2366.0927240	total: 8.07s	remaining: 14.1s
364:	learn: 2365.9322050	total: 8.09s	remaining: 14.1s
365:	learn: 2365.7861987	total: 8.12s	remaining: 14.1s
366:	learn: 2365.6199212	total: 8.14s	remaining: 14s

Подберем лучшие параметры для модели LGBMRegressor с помощью функции GridSearchCV

In [31]:
LGBM = LGBMRegressor()
parametrs = { 'n_estimators': range (10, 51, 10),
             'max_depth': range (1,13, 2)}
grid = GridSearchCV(LGBM, parametrs, scoring='neg_mean_squared_error')
grid.fit(features_train,target_train, categorical_feature=cat_features)
print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 11, 'n_estimators': 50}
-3477453.4548470764

Подберем лучшие параметры для модели XGBRegressor с помощью функции GridSearchCV

In [32]:
xgboost = XGBRegressor()
parametrs = {'max_depth': range (1,13,2)}
grid = GridSearchCV(xgboost, parametrs, scoring='neg_mean_squared_error')
grid.fit(features_train,target_train)
print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 9}
-3142604.9739646767

Обучим модель RandomForestRegressor с подобранными параметрами на валидационной выборке.

In [33]:
%%time
model = RandomForestRegressor(n_estimators=40, 
    max_depth=11, random_state=12345)

model.fit(features_train, target_train) 
start = time.time()
predictions_valid = model.predict(features_valid) # обучите модель на обучающей выборке
end =  time.time()
RF_time = end - start 
print("Время обучения: ",RF_time)
print("RMSE на валидационной выборке: ", mean_squared_error(target_valid, predictions_valid)**0.5)# найдите значение метрики R2 на валидационной выборке

Время обучения:  0.2511632442474365
RMSE на валидационной выборке:  2041.6379652895926
CPU times: user 9.94 s, sys: 14.3 ms, total: 9.95 s
Wall time: 9.97 s

Обучим модель CatBoostRegressor с подобранными параметрами.

In [34]:
%%time
model = CatBoostRegressor(depth= 9, iterations=1000, random_state=12345)
model.fit(features_train, target_train,cat_features=cat_features, eval_set=(features_valid,target_valid)) 
start = time.time()
predictions_valid = model.predict(features_valid) 
end =  time.time()
cat_time = end - start 
print("Время обучения: ",cat_time)
print("RMSE на валидационной выборке: ", mean_squared_error(target_valid, predictions_valid)**0.5)

Learning rate set to 0.115628
0:	learn: 4199.7966955	test: 4196.1756820	best: 4196.1756820 (0)	total: 441ms	remaining: 7m 20s
1:	learn: 3888.5793326	test: 3888.7811421	best: 3888.7811421 (1)	total: 797ms	remaining: 6m 37s
2:	learn: 3620.8205764	test: 3624.2567617	best: 3624.2567617 (2)	total: 1.1s	remaining: 6m 6s
3:	learn: 3387.9187721	test: 3392.7745710	best: 3392.7745710 (3)	total: 1.49s	remaining: 6m 11s
4:	learn: 3189.7770834	test: 3197.1090337	best: 3197.1090337 (4)	total: 1.82s	remaining: 6m 2s
5:	learn: 3020.5322218	test: 3029.5816960	best: 3029.5816960 (5)	total: 2.18s	remaining: 6m 1s
6:	learn: 2878.1228561	test: 2889.8913733	best: 2889.8913733 (6)	total: 2.5s	remaining: 5m 55s
7:	learn: 2753.9942510	test: 2766.8347264	best: 2766.8347264 (7)	total: 2.94s	remaining: 6m 3s
8:	learn: 2648.2223924	test: 2662.3450469	best: 2662.3450469 (8)	total: 3.3s	remaining: 6m 3s
9:	learn: 2560.4080907	test: 2576.4702092	best: 2576.4702092 (9)	total: 3.67s	remaining: 6m 3s
10:	learn: 2480.9435263	test: 2498.1525388	best: 2498.1525388 (10)	total: 3.92s	remaining: 5m 52s
11:	learn: 2415.8719523	test: 2434.3273987	best: 2434.3273987 (11)	total: 4.2s	remaining: 5m 45s
12:	learn: 2359.1081202	test: 2377.6537250	best: 2377.6537250 (12)	total: 4.51s	remaining: 5m 42s
13:	learn: 2304.6002311	test: 2323.8077863	best: 2323.8077863 (13)	total: 4.82s	remaining: 5m 39s
14:	learn: 2261.4781009	test: 2281.9619255	best: 2281.9619255 (14)	total: 5.05s	remaining: 5m 31s
15:	learn: 2223.8063411	test: 2243.1174736	best: 2243.1174736 (15)	total: 5.43s	remaining: 5m 33s
16:	learn: 2191.2432139	test: 2211.4853072	best: 2211.4853072 (16)	total: 5.69s	remaining: 5m 29s
17:	learn: 2165.8962710	test: 2186.8554322	best: 2186.8554322 (17)	total: 6s	remaining: 5m 27s
18:	learn: 2140.7376790	test: 2162.9670199	best: 2162.9670199 (18)	total: 6.32s	remaining: 5m 26s
19:	learn: 2116.8908816	test: 2139.7798356	best: 2139.7798356 (19)	total: 6.63s	remaining: 5m 24s
20:	learn: 2098.0783063	test: 2121.9534104	best: 2121.9534104 (20)	total: 6.94s	remaining: 5m 23s
21:	learn: 2083.1210833	test: 2107.7968812	best: 2107.7968812 (21)	total: 7.27s	remaining: 5m 23s
22:	learn: 2067.4810531	test: 2094.1897708	best: 2094.1897708 (22)	total: 7.62s	remaining: 5m 23s
23:	learn: 2055.6392982	test: 2082.9223902	best: 2082.9223902 (23)	total: 7.88s	remaining: 5m 20s
24:	learn: 2045.7084558	test: 2073.2206840	best: 2073.2206840 (24)	total: 8.28s	remaining: 5m 23s
25:	learn: 2035.9721176	test: 2064.0276220	best: 2064.0276220 (25)	total: 8.64s	remaining: 5m 23s
26:	learn: 2029.3480906	test: 2057.8059642	best: 2057.8059642 (26)	total: 8.9s	remaining: 5m 20s
27:	learn: 2021.4275238	test: 2051.2708636	best: 2051.2708636 (27)	total: 9.15s	remaining: 5m 17s
28:	learn: 2016.2627113	test: 2045.8196391	best: 2045.8196391 (28)	total: 9.38s	remaining: 5m 14s
29:	learn: 2008.6569917	test: 2038.6651668	best: 2038.6651668 (29)	total: 9.61s	remaining: 5m 10s
30:	learn: 2001.8294295	test: 2032.5685842	best: 2032.5685842 (30)	total: 9.97s	remaining: 5m 11s
31:	learn: 1996.0770313	test: 2027.5659058	best: 2027.5659058 (31)	total: 10.3s	remaining: 5m 10s
32:	learn: 1991.7860273	test: 2023.4402077	best: 2023.4402077 (32)	total: 10.5s	remaining: 5m 9s
33:	learn: 1983.2187260	test: 2015.6337330	best: 2015.6337330 (33)	total: 10.8s	remaining: 5m 5s
34:	learn: 1979.4556790	test: 2012.6356539	best: 2012.6356539 (34)	total: 11.1s	remaining: 5m 5s
35:	learn: 1970.9943640	test: 2004.8782695	best: 2004.8782695 (35)	total: 11.3s	remaining: 5m 3s
36:	learn: 1963.6253351	test: 1998.1936004	best: 1998.1936004 (36)	total: 11.6s	remaining: 5m 1s
37:	learn: 1958.2663867	test: 1993.6683336	best: 1993.6683336 (37)	total: 11.8s	remaining: 4m 59s
38:	learn: 1953.7060778	test: 1989.8513947	best: 1989.8513947 (38)	total: 12.1s	remaining: 4m 58s
39:	learn: 1949.4391816	test: 1986.0459750	best: 1986.0459750 (39)	total: 12.4s	remaining: 4m 57s
40:	learn: 1945.0437633	test: 1982.1935435	best: 1982.1935435 (40)	total: 12.7s	remaining: 4m 56s
41:	learn: 1940.6678662	test: 1978.7171253	best: 1978.7171253 (41)	total: 13s	remaining: 4m 56s
42:	learn: 1938.0244141	test: 1976.6277111	best: 1976.6277111 (42)	total: 13.3s	remaining: 4m 54s
43:	learn: 1932.7494840	test: 1972.1243471	best: 1972.1243471 (43)	total: 13.5s	remaining: 4m 54s
44:	learn: 1929.3014038	test: 1969.3973118	best: 1969.3973118 (44)	total: 13.8s	remaining: 4m 53s
45:	learn: 1925.5412825	test: 1966.4462874	best: 1966.4462874 (45)	total: 14.2s	remaining: 4m 53s
46:	learn: 1922.3231748	test: 1963.4172456	best: 1963.4172456 (46)	total: 14.4s	remaining: 4m 51s
47:	learn: 1919.9270021	test: 1961.3138057	best: 1961.3138057 (47)	total: 14.6s	remaining: 4m 50s
48:	learn: 1917.5989168	test: 1959.6326324	best: 1959.6326324 (48)	total: 14.9s	remaining: 4m 49s
49:	learn: 1914.1268791	test: 1956.7884474	best: 1956.7884474 (49)	total: 15.2s	remaining: 4m 49s
50:	learn: 1909.1102005	test: 1952.4562897	best: 1952.4562897 (50)	total: 15.5s	remaining: 4m 47s
51:	learn: 1905.9405819	test: 1949.7811720	best: 1949.7811720 (51)	total: 15.7s	remaining: 4m 45s
52:	learn: 1902.9701835	test: 1947.2878235	best: 1947.2878235 (52)	total: 15.9s	remaining: 4m 43s
53:	learn: 1899.8346695	test: 1944.8379322	best: 1944.8379322 (53)	total: 16.2s	remaining: 4m 43s
54:	learn: 1896.6326756	test: 1942.0656121	best: 1942.0656121 (54)	total: 16.5s	remaining: 4m 43s
55:	learn: 1893.1791056	test: 1939.0450847	best: 1939.0450847 (55)	total: 16.7s	remaining: 4m 42s
56:	learn: 1890.8716841	test: 1937.1317812	best: 1937.1317812 (56)	total: 17s	remaining: 4m 41s
57:	learn: 1886.9578852	test: 1934.0528292	best: 1934.0528292 (57)	total: 17.3s	remaining: 4m 40s
58:	learn: 1884.0221165	test: 1931.8112921	best: 1931.8112921 (58)	total: 17.5s	remaining: 4m 38s
59:	learn: 1882.0767631	test: 1930.5331366	best: 1930.5331366 (59)	total: 17.8s	remaining: 4m 38s
60:	learn: 1880.1341370	test: 1929.0547202	best: 1929.0547202 (60)	total: 18.1s	remaining: 4m 38s
61:	learn: 1878.7350764	test: 1927.9552575	best: 1927.9552575 (61)	total: 18.4s	remaining: 4m 37s
62:	learn: 1876.7472282	test: 1926.2741869	best: 1926.2741869 (62)	total: 18.6s	remaining: 4m 36s
63:	learn: 1875.0792054	test: 1925.0838529	best: 1925.0838529 (63)	total: 18.9s	remaining: 4m 36s
64:	learn: 1872.8295807	test: 1923.1764431	best: 1923.1764431 (64)	total: 19.2s	remaining: 4m 36s
65:	learn: 1870.7594456	test: 1921.5820155	best: 1921.5820155 (65)	total: 19.5s	remaining: 4m 35s
66:	learn: 1868.7891050	test: 1920.3013410	best: 1920.3013410 (66)	total: 19.8s	remaining: 4m 36s
67:	learn: 1865.3569891	test: 1917.4608135	best: 1917.4608135 (67)	total: 20.2s	remaining: 4m 36s
68:	learn: 1864.2249131	test: 1916.4669901	best: 1916.4669901 (68)	total: 20.5s	remaining: 4m 37s
69:	learn: 1861.1167441	test: 1914.6351710	best: 1914.6351710 (69)	total: 20.8s	remaining: 4m 36s
70:	learn: 1858.4222347	test: 1912.5725464	best: 1912.5725464 (70)	total: 21.2s	remaining: 4m 37s
71:	learn: 1856.9183058	test: 1911.3794846	best: 1911.3794846 (71)	total: 21.5s	remaining: 4m 37s
72:	learn: 1854.9036590	test: 1910.0630006	best: 1910.0630006 (72)	total: 21.8s	remaining: 4m 36s
73:	learn: 1853.1675039	test: 1909.1662270	best: 1909.1662270 (73)	total: 22.1s	remaining: 4m 35s
74:	learn: 1851.4903485	test: 1907.8599009	best: 1907.8599009 (74)	total: 22.3s	remaining: 4m 34s
75:	learn: 1849.8678318	test: 1906.8046334	best: 1906.8046334 (75)	total: 22.5s	remaining: 4m 33s
76:	learn: 1847.0292767	test: 1904.4596680	best: 1904.4596680 (76)	total: 22.8s	remaining: 4m 32s
77:	learn: 1845.1889775	test: 1902.9688283	best: 1902.9688283 (77)	total: 23s	remaining: 4m 32s
78:	learn: 1841.7195306	test: 1900.6158504	best: 1900.6158504 (78)	total: 23.3s	remaining: 4m 31s
79:	learn: 1840.3622464	test: 1899.5769953	best: 1899.5769953 (79)	total: 23.6s	remaining: 4m 31s
80:	learn: 1838.8200014	test: 1898.3750323	best: 1898.3750323 (80)	total: 23.9s	remaining: 4m 31s
81:	learn: 1836.7310562	test: 1896.9697093	best: 1896.9697093 (81)	total: 24.2s	remaining: 4m 31s
82:	learn: 1834.7015847	test: 1895.2964501	best: 1895.2964501 (82)	total: 24.4s	remaining: 4m 29s
83:	learn: 1832.9886771	test: 1893.8234139	best: 1893.8234139 (83)	total: 24.7s	remaining: 4m 29s
84:	learn: 1831.0509179	test: 1892.3727416	best: 1892.3727416 (84)	total: 25s	remaining: 4m 29s
85:	learn: 1828.2667342	test: 1889.9977782	best: 1889.9977782 (85)	total: 25.2s	remaining: 4m 28s
86:	learn: 1826.7699279	test: 1888.8701967	best: 1888.8701967 (86)	total: 25.4s	remaining: 4m 27s
87:	learn: 1825.0878031	test: 1888.0032926	best: 1888.0032926 (87)	total: 25.7s	remaining: 4m 25s
88:	learn: 1824.6435730	test: 1887.7747525	best: 1887.7747525 (88)	total: 25.9s	remaining: 4m 25s
89:	learn: 1823.7185211	test: 1887.1776035	best: 1887.1776035 (89)	total: 26.2s	remaining: 4m 24s
90:	learn: 1822.3596128	test: 1886.1952290	best: 1886.1952290 (90)	total: 26.4s	remaining: 4m 24s
91:	learn: 1821.4370885	test: 1885.5899615	best: 1885.5899615 (91)	total: 26.7s	remaining: 4m 23s
92:	learn: 1818.3018782	test: 1883.1738776	best: 1883.1738776 (92)	total: 27s	remaining: 4m 23s
93:	learn: 1816.6406096	test: 1882.1281163	best: 1882.1281163 (93)	total: 27.3s	remaining: 4m 23s
94:	learn: 1815.3598743	test: 1881.2983042	best: 1881.2983042 (94)	total: 27.6s	remaining: 4m 23s
95:	learn: 1814.5349180	test: 1880.7640129	best: 1880.7640129 (95)	total: 27.9s	remaining: 4m 22s
96:	learn: 1812.5816688	test: 1879.3486180	best: 1879.3486180 (96)	total: 28.2s	remaining: 4m 22s
97:	learn: 1811.5986989	test: 1878.8025333	best: 1878.8025333 (97)	total: 28.5s	remaining: 4m 21s
98:	learn: 1810.4607690	test: 1878.2366306	best: 1878.2366306 (98)	total: 28.8s	remaining: 4m 21s
99:	learn: 1809.3441351	test: 1877.4199067	best: 1877.4199067 (99)	total: 29s	remaining: 4m 20s
100:	learn: 1808.2782878	test: 1876.6890142	best: 1876.6890142 (100)	total: 29.3s	remaining: 4m 20s
101:	learn: 1806.2976716	test: 1875.0152311	best: 1875.0152311 (101)	total: 29.5s	remaining: 4m 19s
102:	learn: 1804.4077180	test: 1873.4384903	best: 1873.4384903 (102)	total: 29.8s	remaining: 4m 19s
103:	learn: 1802.8501194	test: 1872.2979382	best: 1872.2979382 (103)	total: 30.1s	remaining: 4m 19s
104:	learn: 1801.5173503	test: 1871.2857928	best: 1871.2857928 (104)	total: 30.5s	remaining: 4m 19s
105:	learn: 1799.6842290	test: 1870.0978819	best: 1870.0978819 (105)	total: 30.7s	remaining: 4m 18s
106:	learn: 1797.1225768	test: 1868.4945346	best: 1868.4945346 (106)	total: 30.9s	remaining: 4m 18s
107:	learn: 1795.7411777	test: 1867.6791133	best: 1867.6791133 (107)	total: 31.3s	remaining: 4m 18s
108:	learn: 1794.1768282	test: 1866.8631379	best: 1866.8631379 (108)	total: 31.5s	remaining: 4m 17s
109:	learn: 1791.9464483	test: 1864.6161983	best: 1864.6161983 (109)	total: 31.8s	remaining: 4m 17s
110:	learn: 1790.7998902	test: 1863.8921793	best: 1863.8921793 (110)	total: 32.2s	remaining: 4m 18s
111:	learn: 1789.2108896	test: 1862.7205801	best: 1862.7205801 (111)	total: 32.5s	remaining: 4m 18s
112:	learn: 1787.7289340	test: 1862.2676275	best: 1862.2676275 (112)	total: 32.9s	remaining: 4m 18s
113:	learn: 1786.5360798	test: 1861.6827679	best: 1861.6827679 (113)	total: 33.1s	remaining: 4m 17s
114:	learn: 1785.2116208	test: 1861.2018515	best: 1861.2018515 (114)	total: 33.4s	remaining: 4m 17s
115:	learn: 1783.6110450	test: 1860.1717355	best: 1860.1717355 (115)	total: 33.7s	remaining: 4m 17s
116:	learn: 1781.8720858	test: 1858.9372684	best: 1858.9372684 (116)	total: 34s	remaining: 4m 16s
117:	learn: 1780.9685176	test: 1858.5758245	best: 1858.5758245 (117)	total: 34.3s	remaining: 4m 16s
118:	learn: 1780.1756459	test: 1857.6634338	best: 1857.6634338 (118)	total: 34.6s	remaining: 4m 16s
119:	learn: 1778.7215145	test: 1856.7720748	best: 1856.7720748 (119)	total: 34.8s	remaining: 4m 15s
120:	learn: 1777.7575518	test: 1856.2188060	best: 1856.2188060 (120)	total: 35.1s	remaining: 4m 15s
121:	learn: 1776.5191260	test: 1855.3284761	best: 1855.3284761 (121)	total: 35.3s	remaining: 4m 14s
122:	learn: 1775.4298971	test: 1854.3746606	best: 1854.3746606 (122)	total: 35.6s	remaining: 4m 13s
123:	learn: 1774.5156482	test: 1853.6462568	best: 1853.6462568 (123)	total: 35.9s	remaining: 4m 13s
124:	learn: 1774.3280327	test: 1853.6278710	best: 1853.6278710 (124)	total: 36.1s	remaining: 4m 12s
125:	learn: 1773.2037819	test: 1853.0449284	best: 1853.0449284 (125)	total: 36.4s	remaining: 4m 12s
126:	learn: 1771.9515994	test: 1852.0521560	best: 1852.0521560 (126)	total: 36.7s	remaining: 4m 12s
127:	learn: 1771.3926287	test: 1851.7753096	best: 1851.7753096 (127)	total: 37s	remaining: 4m 11s
128:	learn: 1770.5277317	test: 1851.1238625	best: 1851.1238625 (128)	total: 37.3s	remaining: 4m 11s
129:	learn: 1769.6916343	test: 1850.4808329	best: 1850.4808329 (129)	total: 37.6s	remaining: 4m 11s
130:	learn: 1768.5007383	test: 1849.7513607	best: 1849.7513607 (130)	total: 37.9s	remaining: 4m 11s
131:	learn: 1767.7750317	test: 1849.4864497	best: 1849.4864497 (131)	total: 38.1s	remaining: 4m 10s
132:	learn: 1767.0126811	test: 1848.9566940	best: 1848.9566940 (132)	total: 38.4s	remaining: 4m 10s
133:	learn: 1766.0189045	test: 1848.2174427	best: 1848.2174427 (133)	total: 38.8s	remaining: 4m 10s
134:	learn: 1765.3489463	test: 1847.6391020	best: 1847.6391020 (134)	total: 39.2s	remaining: 4m 10s
135:	learn: 1764.2592794	test: 1847.0394042	best: 1847.0394042 (135)	total: 39.6s	remaining: 4m 11s
136:	learn: 1763.1295608	test: 1846.5029114	best: 1846.5029114 (136)	total: 40s	remaining: 4m 11s
137:	learn: 1761.9124624	test: 1845.5427395	best: 1845.5427395 (137)	total: 40.3s	remaining: 4m 11s
138:	learn: 1760.9008904	test: 1844.8299679	best: 1844.8299679 (138)	total: 40.6s	remaining: 4m 11s
139:	learn: 1759.7789286	test: 1844.0012315	best: 1844.0012315 (139)	total: 40.9s	remaining: 4m 11s
140:	learn: 1759.3785813	test: 1843.9067490	best: 1843.9067490 (140)	total: 41.2s	remaining: 4m 11s
141:	learn: 1758.6854765	test: 1843.6730498	best: 1843.6730498 (141)	total: 41.5s	remaining: 4m 10s
142:	learn: 1757.7619538	test: 1842.9981356	best: 1842.9981356 (142)	total: 41.7s	remaining: 4m 10s
143:	learn: 1756.5116220	test: 1842.4057948	best: 1842.4057948 (143)	total: 42s	remaining: 4m 9s
144:	learn: 1755.4825053	test: 1841.7974162	best: 1841.7974162 (144)	total: 42.3s	remaining: 4m 9s
145:	learn: 1754.9252811	test: 1841.3220898	best: 1841.3220898 (145)	total: 42.7s	remaining: 4m 9s
146:	learn: 1753.7168702	test: 1840.6183840	best: 1840.6183840 (146)	total: 43s	remaining: 4m 9s
147:	learn: 1752.4179198	test: 1839.8406703	best: 1839.8406703 (147)	total: 43.4s	remaining: 4m 9s
148:	learn: 1751.1193438	test: 1839.4092195	best: 1839.4092195 (148)	total: 43.7s	remaining: 4m 9s
149:	learn: 1750.4876672	test: 1839.0612536	best: 1839.0612536 (149)	total: 44s	remaining: 4m 9s
150:	learn: 1749.7642999	test: 1838.4328975	best: 1838.4328975 (150)	total: 44.3s	remaining: 4m 9s
151:	learn: 1748.8229064	test: 1837.8399842	best: 1837.8399842 (151)	total: 44.6s	remaining: 4m 8s
152:	learn: 1747.8649100	test: 1837.5405981	best: 1837.5405981 (152)	total: 44.8s	remaining: 4m 8s
153:	learn: 1747.0370877	test: 1836.9302140	best: 1836.9302140 (153)	total: 45.1s	remaining: 4m 8s
154:	learn: 1746.6957838	test: 1836.7808685	best: 1836.7808685 (154)	total: 45.5s	remaining: 4m 7s
155:	learn: 1746.1020528	test: 1836.4985582	best: 1836.4985582 (155)	total: 45.8s	remaining: 4m 7s
156:	learn: 1745.1067482	test: 1835.8755851	best: 1835.8755851 (156)	total: 46s	remaining: 4m 7s
157:	learn: 1744.1480639	test: 1835.5573686	best: 1835.5573686 (157)	total: 46.3s	remaining: 4m 6s
158:	learn: 1743.6120941	test: 1835.1999140	best: 1835.1999140 (158)	total: 46.6s	remaining: 4m 6s
159:	learn: 1743.2587378	test: 1835.0879314	best: 1835.0879314 (159)	total: 46.9s	remaining: 4m 6s
160:	learn: 1742.6891968	test: 1834.9846794	best: 1834.9846794 (160)	total: 47.2s	remaining: 4m 5s
161:	learn: 1742.4854716	test: 1834.9851632	best: 1834.9846794 (160)	total: 47.5s	remaining: 4m 5s
162:	learn: 1741.5763044	test: 1834.2135608	best: 1834.2135608 (162)	total: 47.7s	remaining: 4m 4s
163:	learn: 1740.7280903	test: 1833.3943074	best: 1833.3943074 (163)	total: 48s	remaining: 4m 4s
164:	learn: 1739.5878961	test: 1832.4860165	best: 1832.4860165 (164)	total: 48.3s	remaining: 4m 4s
165:	learn: 1738.5443075	test: 1831.8077932	best: 1831.8077932 (165)	total: 48.6s	remaining: 4m 3s
166:	learn: 1737.8383597	test: 1831.3075131	best: 1831.3075131 (166)	total: 48.8s	remaining: 4m 3s
167:	learn: 1736.8513736	test: 1830.9939030	best: 1830.9939030 (167)	total: 49.1s	remaining: 4m 3s
168:	learn: 1735.3778721	test: 1830.3392521	best: 1830.3392521 (168)	total: 49.3s	remaining: 4m 2s
169:	learn: 1734.3788631	test: 1829.8263799	best: 1829.8263799 (169)	total: 49.6s	remaining: 4m 2s
170:	learn: 1733.0290806	test: 1829.0949719	best: 1829.0949719 (170)	total: 49.8s	remaining: 4m 1s
171:	learn: 1732.4165519	test: 1828.8800953	best: 1828.8800953 (171)	total: 50s	remaining: 4m
172:	learn: 1731.2325735	test: 1828.0327021	best: 1828.0327021 (172)	total: 50.3s	remaining: 4m
173:	learn: 1730.4163073	test: 1827.6014514	best: 1827.6014514 (173)	total: 50.7s	remaining: 4m
174:	learn: 1729.8637109	test: 1827.3356476	best: 1827.3356476 (174)	total: 50.9s	remaining: 3m 59s
175:	learn: 1729.5968382	test: 1827.0777719	best: 1827.0777719 (175)	total: 51.2s	remaining: 3m 59s
176:	learn: 1729.0096289	test: 1826.6708418	best: 1826.6708418 (176)	total: 51.5s	remaining: 3m 59s
177:	learn: 1728.4637321	test: 1826.4539992	best: 1826.4539992 (177)	total: 51.8s	remaining: 3m 59s
178:	learn: 1727.7631614	test: 1826.1991444	best: 1826.1991444 (178)	total: 52s	remaining: 3m 58s
179:	learn: 1727.0790328	test: 1825.8523749	best: 1825.8523749 (179)	total: 52.2s	remaining: 3m 57s
180:	learn: 1726.4327560	test: 1825.3091582	best: 1825.3091582 (180)	total: 52.5s	remaining: 3m 57s
181:	learn: 1724.8538051	test: 1824.5422150	best: 1824.5422150 (181)	total: 52.8s	remaining: 3m 57s
182:	learn: 1724.2176166	test: 1824.3677452	best: 1824.3677452 (182)	total: 53.1s	remaining: 3m 56s
183:	learn: 1723.8797612	test: 1824.3283714	best: 1824.3283714 (183)	total: 53.3s	remaining: 3m 56s
184:	learn: 1722.9037115	test: 1823.6714103	best: 1823.6714103 (184)	total: 53.5s	remaining: 3m 55s
185:	learn: 1722.4527885	test: 1823.4277378	best: 1823.4277378 (185)	total: 53.8s	remaining: 3m 55s
186:	learn: 1722.0491394	test: 1823.2970326	best: 1823.2970326 (186)	total: 54s	remaining: 3m 54s
187:	learn: 1720.7848943	test: 1822.2682747	best: 1822.2682747 (187)	total: 54.3s	remaining: 3m 54s
188:	learn: 1720.6355326	test: 1822.2387956	best: 1822.2387956 (188)	total: 54.6s	remaining: 3m 54s
189:	learn: 1720.1233705	test: 1821.7620222	best: 1821.7620222 (189)	total: 55s	remaining: 3m 54s
190:	learn: 1719.2949622	test: 1821.3032976	best: 1821.3032976 (190)	total: 55.4s	remaining: 3m 54s
191:	learn: 1718.7973870	test: 1821.0495890	best: 1821.0495890 (191)	total: 55.6s	remaining: 3m 54s
192:	learn: 1717.4784573	test: 1820.2402920	best: 1820.2402920 (192)	total: 55.9s	remaining: 3m 53s
193:	learn: 1717.0369593	test: 1820.1426879	best: 1820.1426879 (193)	total: 56.1s	remaining: 3m 53s
194:	learn: 1716.4784299	test: 1819.9120231	best: 1819.9120231 (194)	total: 56.4s	remaining: 3m 52s
195:	learn: 1715.9311697	test: 1819.6444379	best: 1819.6444379 (195)	total: 56.6s	remaining: 3m 52s
196:	learn: 1715.6190128	test: 1819.6248440	best: 1819.6248440 (196)	total: 56.8s	remaining: 3m 51s
197:	learn: 1715.0984133	test: 1819.4991558	best: 1819.4991558 (197)	total: 57.1s	remaining: 3m 51s
198:	learn: 1714.5825335	test: 1819.2226722	best: 1819.2226722 (198)	total: 57.4s	remaining: 3m 51s
199:	learn: 1713.9292613	test: 1818.7506656	best: 1818.7506656 (199)	total: 57.8s	remaining: 3m 51s
200:	learn: 1713.2411671	test: 1818.5761986	best: 1818.5761986 (200)	total: 58.1s	remaining: 3m 50s
201:	learn: 1711.9196453	test: 1817.9823728	best: 1817.9823728 (201)	total: 58.3s	remaining: 3m 50s

Обучим модель LGBMRegressor с подобранными параметрами.

In [35]:
%%time
model = LGBMRegressor(max_depth = 11, n_estimators = 50, random_state=12345)
model.fit(features_train, target_train, categorical_feature=cat_features, verbose=100)  
start = time.time()
predictions_valid = model.predict(features_valid) 
end =  time.time()
LGBM_time = end - start 
print("Время обучения: ",LGBM_time)
print("RMSE на валидационной выборке: ", mean_squared_error(target_valid, predictions_valid)**0.5)

Время обучения:  0.32776737213134766
RMSE на валидационной выборке:  1873.7302164169976
CPU times: user 23.3 s, sys: 139 ms, total: 23.5 s
Wall time: 23.6 s

Обучим модель XGBRegressor с подобранными параметрами.

In [36]:
%%time
model = XGBRegressor(max_depth = 9, subsample= 1.0, random_state=12345)
model.fit(features_train, target_train, verbose=100)  
start = time.time()
predictions_valid = model.predict(features_valid) 
end =  time.time()
XGB_time = end - start 
print("Время обучения: ",XGB_time)
print("RMSE на валидационной выборке: ", mean_squared_error(target_valid, predictions_valid)**0.5)

Время обучения:  0.3825232982635498
RMSE на валидационной выборке:  1781.144873344275
CPU times: user 3min 16s, sys: 1.31 s, total: 3min 17s
Wall time: 3min 18s

Обучим модель RandomForestRegressor с подобранными параметрами на тестовой выборке.

In [37]:
%%time
model = RandomForestRegressor(n_estimators=50, 
    max_depth=11, random_state=12345)

model.fit(features_train, target_train)  
predictions_test = model.predict(features_test) 
print("Наилучшая модель")
print("RMSE на тестовой выборке: ", mean_squared_error(target_test, predictions_test)**0.5)# найдите значение метрики R2 на валидационной выборке

Наилучшая модель
RMSE на тестовой выборке:  2051.338263603141
CPU times: user 14.9 s, sys: 855 µs, total: 14.9 s
Wall time: 15.1 s

Обучим модель CatBoostRegressor с подобранными параметрами на тестовой выборке.

In [38]:
%%time
model= CatBoostRegressor(depth= 9, iterations= 100, random_state=12345)
model.fit(features_train, target_train, cat_features=cat_features, eval_set=(features_valid,target_valid)) 
predictions_test = model.predict(features_test) 
print("Наилучшая модель")
print("RMSE на тестовой выборке: ", mean_squared_error(target_test, predictions_test)**0.5)

Learning rate set to 0.471044
0:	learn: 3256.3939544	test: 3261.4007631	best: 3261.4007631 (0)	total: 131ms	remaining: 12.9s
1:	learn: 2649.3757528	test: 2663.2791908	best: 2663.2791908 (1)	total: 254ms	remaining: 12.5s
2:	learn: 2352.6916769	test: 2367.6049187	best: 2367.6049187 (2)	total: 386ms	remaining: 12.5s
3:	learn: 2197.0489226	test: 2217.9696344	best: 2217.9696344 (3)	total: 498ms	remaining: 12s
4:	learn: 2110.8060103	test: 2129.2959365	best: 2129.2959365 (4)	total: 611ms	remaining: 11.6s
5:	learn: 2077.6089815	test: 2098.7308887	best: 2098.7308887 (5)	total: 707ms	remaining: 11.1s
6:	learn: 2052.3309159	test: 2071.6012548	best: 2071.6012548 (6)	total: 803ms	remaining: 10.7s
7:	learn: 2028.5277400	test: 2050.6116791	best: 2050.6116791 (7)	total: 902ms	remaining: 10.4s
8:	learn: 2012.1033379	test: 2035.8508904	best: 2035.8508904 (8)	total: 997ms	remaining: 10.1s
9:	learn: 1994.4391564	test: 2022.8455003	best: 2022.8455003 (9)	total: 1.09s	remaining: 9.86s
10:	learn: 1981.6416242	test: 2009.9900130	best: 2009.9900130 (10)	total: 1.2s	remaining: 9.67s
11:	learn: 1969.6335740	test: 2001.7694464	best: 2001.7694464 (11)	total: 1.29s	remaining: 9.47s
12:	learn: 1949.5519329	test: 1984.5411404	best: 1984.5411404 (12)	total: 1.39s	remaining: 9.3s
13:	learn: 1935.9623159	test: 1972.0959426	best: 1972.0959426 (13)	total: 1.49s	remaining: 9.13s
14:	learn: 1920.9433424	test: 1960.8702944	best: 1960.8702944 (14)	total: 1.59s	remaining: 9.02s
15:	learn: 1914.6672745	test: 1957.2825554	best: 1957.2825554 (15)	total: 1.69s	remaining: 8.87s
16:	learn: 1903.0523973	test: 1948.0758111	best: 1948.0758111 (16)	total: 1.79s	remaining: 8.74s
17:	learn: 1895.7187381	test: 1942.0446437	best: 1942.0446437 (17)	total: 1.88s	remaining: 8.58s
18:	learn: 1888.8459910	test: 1938.1784920	best: 1938.1784920 (18)	total: 1.98s	remaining: 8.46s
19:	learn: 1878.7281424	test: 1931.7440590	best: 1931.7440590 (19)	total: 2.09s	remaining: 8.35s
20:	learn: 1871.1224021	test: 1927.7439492	best: 1927.7439492 (20)	total: 2.19s	remaining: 8.23s
21:	learn: 1865.9951843	test: 1926.2176502	best: 1926.2176502 (21)	total: 2.29s	remaining: 8.11s
22:	learn: 1860.4380098	test: 1922.2430088	best: 1922.2430088 (22)	total: 2.38s	remaining: 7.99s
23:	learn: 1854.7877269	test: 1918.5995237	best: 1918.5995237 (23)	total: 2.48s	remaining: 7.86s
24:	learn: 1848.5116387	test: 1914.8679523	best: 1914.8679523 (24)	total: 2.57s	remaining: 7.72s
25:	learn: 1839.6230864	test: 1908.2331444	best: 1908.2331444 (25)	total: 2.67s	remaining: 7.58s
26:	learn: 1832.2845192	test: 1904.0457205	best: 1904.0457205 (26)	total: 2.76s	remaining: 7.47s
27:	learn: 1829.3317616	test: 1901.8463323	best: 1901.8463323 (27)	total: 2.86s	remaining: 7.35s
28:	learn: 1826.4244399	test: 1900.0340779	best: 1900.0340779 (28)	total: 2.96s	remaining: 7.24s
29:	learn: 1823.1229366	test: 1897.6100751	best: 1897.6100751 (29)	total: 3.05s	remaining: 7.13s
30:	learn: 1815.7278853	test: 1892.3246348	best: 1892.3246348 (30)	total: 3.15s	remaining: 7.02s
31:	learn: 1813.0707636	test: 1891.0745668	best: 1891.0745668 (31)	total: 3.25s	remaining: 6.91s
32:	learn: 1808.7616315	test: 1888.1403029	best: 1888.1403029 (32)	total: 3.35s	remaining: 6.81s
33:	learn: 1803.9037992	test: 1885.8223197	best: 1885.8223197 (33)	total: 3.45s	remaining: 6.7s
34:	learn: 1802.1656620	test: 1885.2689218	best: 1885.2689218 (34)	total: 3.55s	remaining: 6.6s
35:	learn: 1798.1473028	test: 1883.6349137	best: 1883.6349137 (35)	total: 3.65s	remaining: 6.49s
36:	learn: 1795.6553522	test: 1880.6296583	best: 1880.6296583 (36)	total: 3.75s	remaining: 6.38s
37:	learn: 1793.1115457	test: 1879.1839944	best: 1879.1839944 (37)	total: 3.86s	remaining: 6.29s
38:	learn: 1790.5677888	test: 1877.8084263	best: 1877.8084263 (38)	total: 3.97s	remaining: 6.21s
39:	learn: 1787.3635666	test: 1876.1037266	best: 1876.1037266 (39)	total: 4.07s	remaining: 6.1s
40:	learn: 1784.4198444	test: 1873.7569253	best: 1873.7569253 (40)	total: 4.16s	remaining: 5.99s
41:	learn: 1781.5581600	test: 1872.1964765	best: 1872.1964765 (41)	total: 4.25s	remaining: 5.88s
42:	learn: 1777.5677816	test: 1868.5179335	best: 1868.5179335 (42)	total: 4.35s	remaining: 5.77s
43:	learn: 1771.6714280	test: 1864.2640153	best: 1864.2640153 (43)	total: 4.44s	remaining: 5.65s
44:	learn: 1768.5505044	test: 1862.9808807	best: 1862.9808807 (44)	total: 4.54s	remaining: 5.54s
45:	learn: 1766.6825888	test: 1862.0102028	best: 1862.0102028 (45)	total: 4.64s	remaining: 5.44s
46:	learn: 1763.6978810	test: 1861.0935664	best: 1861.0935664 (46)	total: 4.73s	remaining: 5.34s
47:	learn: 1762.1591406	test: 1859.9706201	best: 1859.9706201 (47)	total: 4.83s	remaining: 5.23s
48:	learn: 1759.8561715	test: 1859.0764033	best: 1859.0764033 (48)	total: 4.92s	remaining: 5.12s
49:	learn: 1756.7146096	test: 1857.0496189	best: 1857.0496189 (49)	total: 5.02s	remaining: 5.02s
50:	learn: 1755.3477823	test: 1856.3385910	best: 1856.3385910 (50)	total: 5.11s	remaining: 4.91s
51:	learn: 1753.1647751	test: 1855.3201885	best: 1855.3201885 (51)	total: 5.21s	remaining: 4.81s
52:	learn: 1751.4715764	test: 1854.5949295	best: 1854.5949295 (52)	total: 5.32s	remaining: 4.71s
53:	learn: 1747.8280097	test: 1851.7905764	best: 1851.7905764 (53)	total: 5.42s	remaining: 4.61s
54:	learn: 1744.8764309	test: 1850.3780429	best: 1850.3780429 (54)	total: 5.51s	remaining: 4.51s
55:	learn: 1742.8421015	test: 1849.4278538	best: 1849.4278538 (55)	total: 5.61s	remaining: 4.41s
56:	learn: 1739.8862148	test: 1848.1155366	best: 1848.1155366 (56)	total: 5.71s	remaining: 4.3s
57:	learn: 1737.1287023	test: 1845.6683076	best: 1845.6683076 (57)	total: 5.8s	remaining: 4.2s
58:	learn: 1735.5705206	test: 1844.9251064	best: 1844.9251064 (58)	total: 5.9s	remaining: 4.1s
59:	learn: 1733.3288705	test: 1843.1199106	best: 1843.1199106 (59)	total: 6s	remaining: 4s
60:	learn: 1731.3530020	test: 1842.9639614	best: 1842.9639614 (60)	total: 6.09s	remaining: 3.9s
61:	learn: 1729.6704739	test: 1842.6117432	best: 1842.6117432 (61)	total: 6.2s	remaining: 3.8s
62:	learn: 1727.1271421	test: 1841.9931048	best: 1841.9931048 (62)	total: 6.3s	remaining: 3.7s
63:	learn: 1724.8132808	test: 1840.7823738	best: 1840.7823738 (63)	total: 6.41s	remaining: 3.61s
64:	learn: 1722.9996637	test: 1840.7418515	best: 1840.7418515 (64)	total: 6.5s	remaining: 3.5s
65:	learn: 1720.2281246	test: 1839.1738453	best: 1839.1738453 (65)	total: 6.6s	remaining: 3.4s
66:	learn: 1718.1371238	test: 1837.8786058	best: 1837.8786058 (66)	total: 6.7s	remaining: 3.3s
67:	learn: 1717.7694986	test: 1837.6746051	best: 1837.6746051 (67)	total: 6.8s	remaining: 3.2s
68:	learn: 1715.8795187	test: 1837.1186685	best: 1837.1186685 (68)	total: 6.9s	remaining: 3.1s
69:	learn: 1714.5479573	test: 1835.6043197	best: 1835.6043197 (69)	total: 6.99s	remaining: 3s
70:	learn: 1712.7404683	test: 1835.3161083	best: 1835.3161083 (70)	total: 7.09s	remaining: 2.9s
71:	learn: 1711.0143770	test: 1834.5195956	best: 1834.5195956 (71)	total: 7.2s	remaining: 2.8s
72:	learn: 1709.8168995	test: 1833.8018634	best: 1833.8018634 (72)	total: 7.29s	remaining: 2.69s
73:	learn: 1708.7585866	test: 1833.1816039	best: 1833.1816039 (73)	total: 7.39s	remaining: 2.6s
74:	learn: 1707.9426902	test: 1832.6113838	best: 1832.6113838 (74)	total: 7.49s	remaining: 2.5s
75:	learn: 1707.1185017	test: 1832.4995432	best: 1832.4995432 (75)	total: 7.59s	remaining: 2.4s
76:	learn: 1703.9694533	test: 1830.9395917	best: 1830.9395917 (76)	total: 7.69s	remaining: 2.3s
77:	learn: 1702.8047810	test: 1830.3984487	best: 1830.3984487 (77)	total: 7.79s	remaining: 2.2s
78:	learn: 1700.2592244	test: 1829.6256504	best: 1829.6256504 (78)	total: 7.89s	remaining: 2.1s
79:	learn: 1698.4595147	test: 1828.3148110	best: 1828.3148110 (79)	total: 7.99s	remaining: 2s
80:	learn: 1697.9009923	test: 1827.8962874	best: 1827.8962874 (80)	total: 8.08s	remaining: 1.9s
81:	learn: 1696.4793187	test: 1827.7415621	best: 1827.7415621 (81)	total: 8.19s	remaining: 1.8s
82:	learn: 1695.4041218	test: 1827.7185609	best: 1827.7185609 (82)	total: 8.28s	remaining: 1.7s
83:	learn: 1694.4907539	test: 1827.4118659	best: 1827.4118659 (83)	total: 8.39s	remaining: 1.6s
84:	learn: 1692.7835801	test: 1827.2630008	best: 1827.2630008 (84)	total: 8.48s	remaining: 1.5s
85:	learn: 1691.9658703	test: 1826.6842039	best: 1826.6842039 (85)	total: 8.59s	remaining: 1.4s
86:	learn: 1691.8749160	test: 1826.6880125	best: 1826.6842039 (85)	total: 8.68s	remaining: 1.3s
87:	learn: 1691.2259048	test: 1826.1932080	best: 1826.1932080 (87)	total: 8.78s	remaining: 1.2s
88:	learn: 1690.7858552	test: 1826.2137293	best: 1826.1932080 (87)	total: 8.88s	remaining: 1.1s
89:	learn: 1689.9669875	test: 1826.1052376	best: 1826.1052376 (89)	total: 8.97s	remaining: 997ms
90:	learn: 1688.6083907	test: 1825.7140704	best: 1825.7140704 (90)	total: 9.07s	remaining: 897ms
91:	learn: 1686.6769559	test: 1825.1954444	best: 1825.1954444 (91)	total: 9.17s	remaining: 798ms
92:	learn: 1684.0124265	test: 1824.7924671	best: 1824.7924671 (92)	total: 9.27s	remaining: 698ms
93:	learn: 1680.8968720	test: 1823.3508876	best: 1823.3508876 (93)	total: 9.37s	remaining: 598ms
94:	learn: 1679.8310132	test: 1823.2521452	best: 1823.2521452 (94)	total: 9.47s	remaining: 498ms
95:	learn: 1678.8096971	test: 1822.5896680	best: 1822.5896680 (95)	total: 9.57s	remaining: 399ms
96:	learn: 1676.5932000	test: 1822.1976560	best: 1822.1976560 (96)	total: 9.67s	remaining: 299ms
97:	learn: 1675.4089079	test: 1821.8938563	best: 1821.8938563 (97)	total: 9.77s	remaining: 199ms
98:	learn: 1674.4478504	test: 1821.5372206	best: 1821.5372206 (98)	total: 9.87s	remaining: 99.7ms
99:	learn: 1672.7510013	test: 1821.1391766	best: 1821.1391766 (99)	total: 9.97s	remaining: 0us

bestTest = 1821.139177
bestIteration = 99

Наилучшая модель
RMSE на тестовой выборке:  1817.8140722395053
CPU times: user 10.5 s, sys: 96.1 ms, total: 10.6 s
Wall time: 12.4 s

Обучим модель LGBMRegressor с подобранными параметрами на тестовой выборке.

In [39]:
%%time
model = LGBMRegressor(max_depth = 11, n_estimators = 50, random_state=12345)
model.fit(features_train, target_train, categorical_feature=cat_features, verbose=100)  
predictions_test = model.predict(features_test) 
print("Наилучшая модель")
print("RMSE на тестовой выборке: ", mean_squared_error(target_test, predictions_test)**0.5)

Наилучшая модель
RMSE на тестовой выборке:  1870.2445727060976
CPU times: user 1min 28s, sys: 483 ms, total: 1min 29s
Wall time: 1min 29s

Обучим модель XGBRegressor с подобранными параметрами на тестовой выборке.

In [40]:
%%time
model = XGBRegressor(max_depth = 9, subsample= 1.0, random_state=12345)
model.fit(features_train, target_train, verbose=100)  
predictions_test = model.predict(features_test) 
print("Наилучшая модель")
print("RMSE на тестовой выборке: ", mean_squared_error(target_test, predictions_test)**0.5)

Наилучшая модель
RMSE на тестовой выборке:  1787.8496801670258
CPU times: user 2min 8s, sys: 478 ms, total: 2min 9s
Wall time: 2min 10s

# Вывод

На данном этапе:

- обучили модели RandomForestRegressor, CatBoostRegressor, LGBMRegressor, XGBRegressor .
- подобрали гиперпараметры.

## Анализ моделей

Проанализируем скорость работы и качество моделей:

Для заказчика важны:
- качество предсказания;
- скорость предсказания;
- время обучения.

In [ ]:
<div class="alert alert-block alert-warning">
<b>Изменения:</b> Внесла 
</div>

In [42]:
results = {
    'Model' : ['RandomForestRegressor', 'CatBoostRegressor','LGBMRegressor', 'XGBRegressor'],
    'Valid RMSE' :pd.Series([2041.6, 1755.7, 1873.7,1781.1]),
    'Valid Time, sec': pd.Series([10.0, 312, 23.6, 198]),
    'Time Prediction': pd.Series([0.25, 1, 0.32, 0.36]),
    'Test RMSE' :pd.Series([2051.3, 1817.8, 1870.2,1787.8]),
    'Test Time, sec': pd.Series([15.1, 12.4, 89, 130])
    }
display(pd.DataFrame(results))

,Model,Valid RMSE,"Valid Time, sec",Time Prediction,Test RMSE,"Test Time, sec"
0,RandomForestRegressor,2041.6,10.0,0.25,2051.3,15.1
1,CatBoostRegressor,1755.7,312.0,1.00,1817.8,12.4
2,LGBMRegressor,1873.7,23.6,0.32,1870.2,89.0
3,XGBRegressor,1781.1,198.0,0.36,1787.8,130.0

# Вывод

- Модель CatBoostRegressor на валидационной выборке показала наилучшую метрику RMSE.
- Модель XGBRegressor обладает на тестовой выборке наилучшим показателем метрики RMSE, но при этом наихудшим результатом времени.
- Модель CatBoostRegressor обладает на тестовой выборке вторым показателем метрики RMSE, но при этом лучший результат по времени.
- Время предсказания у модели CatBoostRegressor дольше всех остальных моделей.